-- FACEBOOK ADS CONTENT PART 4 (Modules 8-10)
-- GOLD STANDARD EDITION: Tables, Deep Theory, Pro Tips
-- Execute after FB_ADS_01_MODULE_1_FIXED.sql

DO $$
DECLARE
    v_course_id UUID := '123e4567-e89b-12d3-a456-426614174002';
    v_mod8 UUID; v_mod9 UUID; v_mod10 UUID;
BEGIN
    SELECT id INTO v_mod8 FROM modules WHERE course_id = v_course_id AND ordering = 8;
    SELECT id INTO v_mod9 FROM modules WHERE course_id = v_course_id AND ordering = 9;
    SELECT id INTO v_mod10 FROM modules WHERE course_id = v_course_id AND ordering = 10;

    -- MODULE 8: COMPLIANCE, ETHICS & TROUBLESHOOTING
    
    INSERT INTO lessons (module_id, title, ordering, video_url, content) VALUES
    (v_mod8, 'Facebook Ad Policies & Common Violations', 1, 'https://www.youtube.com/watch?v=K53x7gaZJ2E',
    '<h2>The Landmines</h2><p>One wrong move and your business is dead. Seriously.</p><table style="width:100%;border-collapse:collapse;margin:20px 0;"><tr><th style="border:1px solid #ddd;padding:10px;">Violation</th><th style="border:1px solid #ddd;padding:10px;">Example</th><th style="border:1px solid #ddd;padding:10px;">Why it is Banned</th></tr><tr><td style="border:1px solid #ddd;padding:10px;">Personal Attributes</td><td style="border:1px solid #ddd;padding:10px;">"Are you fat?"</td><td style="border:1px solid #ddd;padding:10px;">Calling out user insecurity is predatory.</td></tr><tr><td style="border:1px solid #ddd;padding:10px;">False Promises</td><td style="border:1px solid #ddd;padding:10px;">"Make $1,000 in 1 hour."</td><td style="border:1px solid #ddd;padding:10px;">Non-functional/Misleading claims destroy trust.</td></tr><tr><td style="border:1px solid #ddd;padding:10px;">Before/After</td><td style="border:1px solid #ddd;padding:10px;">Zoomed in belly fat photos.</td><td style="border:1px solid #ddd;padding:10px;">Implies unrealistic results for everyone.</td></tr></table><div style="background-color: #fff3cd; border-left: 5px solid #ffc107; padding: 20px; border-radius: 5px; margin: 20px 0;"><h3 style="color: #856404; margin-top: 0;">💡 Pro Tip: The "You" Rule</h3><p>Avoid using the word "You" too much. Instead of "Do YOU have debt?", say "Debt can be overwhelming." Focus on the problem, not the person.</p></div><div style="background-color: #ffffff; border: 2px solid #1877f2; padding: 20px; border-radius: 8px; margin: 20px 0;"><h3 style="color: #1877f2; margin-top: 0; text-align: center;">📝 Knowledge Check</h3><div style="margin-bottom: 15px; padding: 10px; border-bottom: 1px solid #eee;"><strong>1. Crypto/Loans?</strong><details><summary>Reveal</summary><p>Restricted. You need written permission from Facebook to run these.</p></details></div><div style="margin-bottom: 15px; padding: 10px; border-bottom: 1px solid #eee;"><strong>2. Landing Page check?</strong><details><summary>Reveal</summary><p>Facebook crawls your landing page too. If the page violates policy, the ad is rejected.</p></details></div><div style="margin-bottom: 15px; padding: 10px; border-bottom: 1px solid #eee;"><strong>3. Circumventing Systems?</strong><details><summary>Reveal</summary><p>Trying to hide hidden text or use cloakers. Instant permanent ban.</p></details></div><div style="margin-bottom: 15px; padding: 10px; border-bottom: 1px solid #eee;"><strong>4. Discrimination?</strong><details><summary>Reveal</summary><p>You cannot exclude races or genders for Housing, Employment, or Credit ads (HEC).</p></details></div><div style="margin-bottom: 15px; padding: 10px; border-bottom: 1px solid #eee;"><strong>5. Brand Assets?</strong><details><summary>Reveal</summary><p>Don''t use the Facebook logo in your ad creative.</p></details></div></div>')
    ON CONFLICT (module_id, ordering) DO UPDATE SET title=EXCLUDED.title, content=EXCLUDED.content;

    INSERT INTO lessons (module_id, title, ordering, video_url, content) VALUES
    (v_mod8, 'Getting Unbanned & Appeal Process', 2, 'https://www.youtube.com/watch?v=62CDBU7Hl2E',
    '<h2>The Jailbreak</h2><p>It happens to the best of us.</p><p><strong>Step 1: Check Account Quality.</strong><br>Go to business.facebook.com/accountquality. See the exact reason.</p><p><strong>Step 2: Request Review.</strong><br>If it says "Identity Confirmation Failed", upload your ID. If it is an ad rejection, click "Request Review".</p><div style="background-color: #f8d7da; border-left: 5px solid #dc3545; padding: 20px; border-radius: 5px; margin: 20px 0;"><h3 style="color: #721c24; margin-top: 0;">🚨 WARNING</h3><p>Do NOT create a new ad account immediately. Facebook tracks your IP, Browser Fingerprint, and Credit Card. They will ban the new one too, and then ban your profile permanently.</p></div><div style="background-color: #ffffff; border: 2px solid #1877f2; padding: 20px; border-radius: 8px; margin: 20px 0;"><h3 style="color: #1877f2; margin-top: 0; text-align: center;">📝 Knowledge Check</h3><div style="margin-bottom: 15px; padding: 10px; border-bottom: 1px solid #eee;"><strong>1. Chat Support?</strong><details><summary>Reveal</summary><p>Real humans exist. Go to Help Section > Contact Support. Be polite.</p></details></div><div style="margin-bottom: 15px; padding: 10px; border-bottom: 1px solid #eee;"><strong>2. Feedback Score?</strong><details><summary>Reveal</summary><p>If customers rate your shipping speed as slow, Facebook can ban you.</p></details></div><div style="margin-bottom: 15px; padding: 10px; border-bottom: 1px solid #eee;"><strong>3. Agency Assets?</strong><details><summary>Reveal</summary><p>If you are an admin on a banned client account, it can hurt your own reliability score.</p></details></div><div style="margin-bottom: 15px; padding: 10px; border-bottom: 1px solid #eee;"><strong>4. 2FA?</strong><details><summary>Reveal</summary><p>Mandatory. If you don''t have 2FA, you might be restricted.</p></details></div><div style="margin-bottom: 15px; padding: 10px; border-bottom: 1px solid #eee;"><strong>5. "Final Decision"?</strong><details><summary>Reveal</summary><p>Usually means Game Over. Time to use a partner/family member''s profile (with permission).</p></details></div></div>')
    ON CONFLICT (module_id, ordering) DO UPDATE SET title=EXCLUDED.title, content=EXCLUDED.content;

    INSERT INTO lessons (module_id, title, ordering, video_url, content) VALUES
    (v_mod8, 'Ethical Advertising Practices', 3, 'https://www.youtube.com/watch?v=8xM4wC7ZBmE',
    '<h2>White Hat vs Black Hat</h2><p>Long term success requires ethics.</p><ul><li><strong>Transparency:</strong> Be clear about what they are buying and the price (including shipping).</li><li><strong>Privacy:</strong> Respect GDPR and user data rights.</li><li><strong>Inclusion:</strong> Represent diverse groups in your creative.</p><div style="background-color: #f0f8ff; border-left: 5px solid #1877f2; padding: 20px; border-radius: 5px; margin: 20px 0;"><h3 style="color: #1877f2; margin-top: 0;">🛠 Practical Exercise</h3><p><strong>The Mom Test:</strong> Look at your ad. Would you be comfortable showing it to your mother? If it feels "Scammy" or "Gross", change it.</p></div><div style="background-color: #ffffff; border: 2px solid #1877f2; padding: 20px; border-radius: 8px; margin: 20px 0;"><h3 style="color: #1877f2; margin-top: 0; text-align: center;">📝 Knowledge Check</h3><div style="margin-bottom: 15px; padding: 10px; border-bottom: 1px solid #eee;"><strong>1. Fake Scarcity?</strong><details><summary>Reveal</summary><p>Using countdown timers that reset every time page loads. Unethical.</p></details></div><div style="margin-bottom: 15px; padding: 10px; border-bottom: 1px solid #eee;"><strong>2. Fake Testimonials?</strong><details><summary>Reveal</summary><p>Illegal in many countries and against terms of service.</p></details></div><div style="margin-bottom: 15px; padding: 10px; border-bottom: 1px solid #eee;"><strong>3. Blind links?</strong><details><summary>Reveal</summary><p>Using bit.ly to hide destination. Suspicious.</p></details></div><div style="margin-bottom: 15px; padding: 10px; border-bottom: 1px solid #eee;"><strong>4. Data sharing?</strong><details><summary>Reveal</summary><p>Selling your lead list to others without consent. Huge violation.</p></details></div><div style="margin-bottom: 15px; padding: 10px; border-bottom: 1px solid #eee;"><strong>5. Political ads?</strong><details><summary>Reveal</summary><p>Must go through strict verification process.</p></details></div></div>')
    ON CONFLICT (module_id, ordering) DO UPDATE SET title=EXCLUDED.title, content=EXCLUDED.content;

    INSERT INTO lessons (module_id, title, ordering, video_url, content) VALUES
    (v_mod8, 'Troubleshooting Disapproved Ads', 4, 'https://www.youtube.com/watch?v=3RkBdJYUL7w',
    '<h2>Computer Says No</h2><p>How to fix specific errors.</p><table style="width:100%;border-collapse:collapse;margin:20px 0;"><tr><th style="border:1px solid #ddd;padding:10px;">Error</th><th style="border:1px solid #ddd;padding:10px;">Fix</th></tr><tr><td style="border:1px solid #ddd;padding:10px;">Too much text in image</td><td style="border:1px solid #ddd;padding:10px;">Reduce font size or move text to caption.</td></tr><tr><td style="border:1px solid #ddd;padding:10px;">Non-functional Landing Page</td><td style="border:1px solid #ddd;padding:10px;">Check page speed. Check 404s.</td></tr><tr><td style="border:1px solid #ddd;padding:10px;">Unacceptable Business Practice</td><td style="border:1px solid #ddd;padding:10px;">Vague. Usually means business model (MLM, Dropshipping spam) is flagged.</td></tr></table><div style="background-color: #ffffff; border: 2px solid #1877f2; padding: 20px; border-radius: 8px; margin: 20px 0;"><h3 style="color: #1877f2; margin-top: 0; text-align: center;">📝 Knowledge Check</h3><div style="margin-bottom: 15px; padding: 10px; border-bottom: 1px solid #eee;"><strong>1. Appeal button missing?</strong><details><summary>Reveal</summary><p>Contact support directly.</p></details></div><div style="margin-bottom: 15px; padding: 10px; border-bottom: 1px solid #eee;"><strong>2. Alcohol ads?</strong><details><summary>Reveal</summary><p>Allowed but must target Age 18+ (or 21+ depending on country).</p></details></div><div style="margin-bottom: 15px; padding: 10px; border-bottom: 1px solid #eee;"><strong>3. Dating ads?</strong><details><summary>Reveal</summary><p>Allowed but restricted targeting categories.</p></details></div><div style="margin-bottom: 15px; padding: 10px; border-bottom: 1px solid #eee;"><strong>4. Glitches?</strong><details><summary>Reveal</summary><p>Sometimes Facebook rejects good ads by mistake. Just appeal.</p></details></div><div style="margin-bottom: 15px; padding: 10px; border-bottom: 1px solid #eee;"><strong>5. Preview link?</strong><details><summary>Reveal</summary><p>Send preview to client to verify BEFORE publishing.</p></details></div></div>')
    ON CONFLICT (module_id, ordering) DO UPDATE SET title=EXCLUDED.title, content=EXCLUDED.content;

    INSERT INTO lessons (module_id, title, ordering, video_url, content) VALUES
    (v_mod8, 'Navigating iOS14+ Privacy Changes', 5, 'https://www.youtube.com/watch?v=K53x7gaZJ2E',
    '<h2>The Apple Apocalypse</h2><p>In 2021, Apple killed the cookie. Here is how we survived.</p><p><strong>The Fix:</strong><br>1. Verify Domain.<br>2. Configure AEM (Aggregated Event Measurement).<br>3. Use CAPI (Conversions API).<br>4. Capture Emails (First Party Data).</p><div style="background-color: #ffffff; border: 2px solid #1877f2; padding: 20px; border-radius: 8px; margin: 20px 0;"><h3 style="color: #1877f2; margin-top: 0; text-align: center;">📝 Knowledge Check</h3><div style="margin-bottom: 15px; padding: 10px; border-bottom: 1px solid #eee;"><strong>1. PCM?</strong><details><summary>Reveal</summary><p>Private Click Measurement. Apple''s protocol for restricting data.</p></details></div><div style="margin-bottom: 15px; padding: 10px; border-bottom: 1px solid #eee;"><strong>2. 72-hour delay?</strong><details><summary>Reveal</summary><p>Data is no longer real-time for iOS users.</p></details></div><div style="margin-bottom: 15px; padding: 10px; border-bottom: 1px solid #eee;"><strong>3. Modeled data?</strong><details><summary>Reveal</summary><p>Facebook "guesses" some conversions based on statistical modeling.</p></details></div><div style="margin-bottom: 15px; padding: 10px; border-bottom: 1px solid #eee;"><strong>4. Retargeting impact?</strong><details><summary>Reveal</summary><p>Website retargeting audiences are smaller. Use Video View retargeting instead (On-platform data).</p></details></div><div style="margin-bottom: 15px; padding: 10px; border-bottom: 1px solid #eee;"><strong>5. Solution?</strong><details><summary>Reveal</summary><p>Focus on broader targeting and better creative.</p></details></div></div>')
    ON CONFLICT (module_id, ordering) DO UPDATE SET title=EXCLUDED.title, content=EXCLUDED.content;


    -- MODULE 9: REAL-WORLD CASE STUDIES
    
    INSERT INTO lessons (module_id, title, ordering, video_url, content) VALUES
    (v_mod9, 'E-commerce Funnel Build', 1, 'https://www.youtube.com/watch?v=8xM4wC7ZBmE',
    '<h2>Selling Physical Products</h2><p><strong>The "Tripwire" Funnel:</strong><br>1. Ad: 50% Off Flash Sale (Impulse Buy).<br>2. Landing Page: Product A ($20).<br>3. Checkout Upsell: Product B (Complementary, $15).<br>4. Email Sequence: Product C (High Ticket).</p><div style="background-color: #f0f8ff; border-left: 5px solid #1877f2; padding: 20px; border-radius: 5px; margin: 20px 0;"><h3 style="color: #1877f2; margin-top: 0;">🛠 Practical Exercise</h3><p><strong>Offer Construction:</strong> Don''t just sell a "Watch". Sell a "Gentleman''s Starter Kit" (Watch + Cufflinks + Box). Bundles increase AOV (Average Order Value).</p></div><div style="background-color: #ffffff; border: 2px solid #1877f2; padding: 20px; border-radius: 8px; margin: 20px 0;"><h3 style="color: #1877f2; margin-top: 0; text-align: center;">📝 Knowledge Check</h3><div style="margin-bottom: 15px; padding: 10px; border-bottom: 1px solid #eee;"><strong>1. Best Creative?</strong><details><summary>Reveal</summary><p>Carousel or Collection ads showing variety.</p></details></div><div style="margin-bottom: 15px; padding: 10px; border-bottom: 1px solid #eee;"><strong>2. Optimization?</strong><details><summary>Reveal</summary><p>Optimize for Purchase (not Add to Cart).</p></details></div><div style="margin-bottom: 15px; padding: 10px; border-bottom: 1px solid #eee;"><strong>3. Abandoned Cart?</strong><details><summary>Reveal</summary><p>Retarget people who added to cart but didn''t buy. 10% discount.</p></details></div><div style="margin-bottom: 15px; padding: 10px; border-bottom: 1px solid #eee;"><strong>4. User Generated Content (UGC)?</strong><details><summary>Reveal</summary><p>Videos of real customers unboxing usually beat studio photos.</p></details></div><div style="margin-bottom: 15px; padding: 10px; border-bottom: 1px solid #eee;"><strong>5. Seasonality?</strong><details><summary>Reveal</summary><p>Q4 (Nov-Dec) is most expensive but highest volume.</p></details></div></div>')
    ON CONFLICT (module_id, ordering) DO UPDATE SET title=EXCLUDED.title, content=EXCLUDED.content;

    INSERT INTO lessons (module_id, title, ordering, video_url, content) VALUES
    (v_mod9, 'Local Business Lead Gen Campaign', 2, 'https://www.youtube.com/watch?v=K53x7gaZJ2E',
    '<h2>The "Crazy Offer" Strategy</h2><p>For Gyms, Dentists, Real Estate.<br><strong>Concept:</strong> "Free Teeth Whitening" (Loss Leader).<br><strong>Goal:</strong> Get them in the door, then upsell Braces/Implants.</p><div style="background-color: #ffffff; border: 2px solid #1877f2; padding: 20px; border-radius: 8px; margin: 20px 0;"><h3 style="color: #1877f2; margin-top: 0; text-align: center;">📝 Knowledge Check</h3><div style="margin-bottom: 15px; padding: 10px; border-bottom: 1px solid #eee;"><strong>1. Lead Forms?</strong><details><summary>Reveal</summary><p>Use On-Facebook forms. They convert higher than websites for local.</p></details></div><div style="margin-bottom: 15px; padding: 10px; border-bottom: 1px solid #eee;"><strong>2. Targeting?</strong><details><summary>Reveal</summary><p>Open targeting + Radius (5 miles). Let copy do the filtering.</p></details></div><div style="margin-bottom: 15px; padding: 10px; border-bottom: 1px solid #eee;"><strong>3. The "Callout"?</strong><details><summary>Reveal</summary><p>"Hey [CITY NAME]!" in the first line.</p></details></div><div style="margin-bottom: 15px; padding: 10px; border-bottom: 1px solid #eee;"><strong>4. Follow up?</strong><details><summary>Reveal</summary><p>Speed is everything. Call within 5 mins.</p></details></div><div style="margin-bottom: 15px; padding: 10px; border-bottom: 1px solid #eee;"><strong>5. Image?</strong><details><summary>Reveal</summary><p>Photo of the actual staff/location (Not stock photos).</p></details></div></div>')
    ON CONFLICT (module_id, ordering) DO UPDATE SET title=EXCLUDED.title, content=EXCLUDED.content;

    INSERT INTO lessons (module_id, title, ordering, video_url, content) VALUES
    (v_mod9, 'Digital Product Launch Strategy', 3, 'https://www.youtube.com/watch?v=62CDBU7Hl2E',
    '<h2>The PLF (Product Launch Formula)</h2><p><strong>Phase 1: Pre-Launch (Lead Gen).</strong><br>Ad: "Free Masterclass" or "Waitlist". Build the email list.</p><p><strong>Phase 2: Launch (Sales).</strong><br>Ad: "Doors Open". Target the email list + Lookalikes.</p><p><strong>Phase 3: Close (Scarcity).</strong><br>Ad: "Closing Tonight". Retargeting only.</p><div style="background-color: #ffffff; border: 2px solid #1877f2; padding: 20px; border-radius: 8px; margin: 20px 0;"><h3 style="color: #1877f2; margin-top: 0; text-align: center;">📝 Knowledge Check</h3><div style="margin-bottom: 15px; padding: 10px; border-bottom: 1px solid #eee;"><strong>1. Webinar funnel?</strong><details><summary>Reveal</summary><p>Ad -> Registration -> Watch Webinar -> Pitch -> Buy.</p></details></div><div style="margin-bottom: 15px; padding: 10px; border-bottom: 1px solid #eee;"><strong>2. High Ticket?</strong><details><summary>Reveal</summary><p>If price > $1,000, send to "Book a Call" instead of "Buy Now".</p></details></div><div style="margin-bottom: 15px; padding: 10px; border-bottom: 1px solid #eee;"><strong>3. Social Proof?</strong><details><summary>Reveal</summary><p>Testimonials are the most critical asset for digital products.</p></details></div><div style="margin-bottom: 15px; padding: 10px; border-bottom: 1px solid #eee;"><strong>4. Earnings Claims?</strong><details><summary>Reveal</summary><p>Be careful. Listing specific $ amounts can get banned.</p></details></div><div style="margin-bottom: 15px; padding: 10px; border-bottom: 1px solid #eee;"><strong>5. Refund policy?</strong><details><summary>Reveal</summary><p>Good guarantee increases conversion rate.</p></details></div></div>')
    ON CONFLICT (module_id, ordering) DO UPDATE SET title=EXCLUDED.title, content=EXCLUDED.content;

    INSERT INTO lessons (module_id, title, ordering, video_url, content) VALUES
    (v_mod9, 'Agency Client Campaign Audit', 4, 'https://www.youtube.com/watch?v=3RkBdJYUL7w',
    '<h2>How to Fix a Broken Account</h2><p>Clients pay you to find problems. Here is your checklist:</p><ol><li><strong>Tracking:</strong> Is Pixel firing?</li><li><strong>Structure:</strong> Is it chaotic? Consolidate ad sets.</li><li><strong>Creative:</strong> Are they testing new things?</li><li><strong>Offer:</strong> Is the offer actually good?</li></ol><div style="background-color: #f0f8ff; border-left: 5px solid #1877f2; padding: 20px; border-radius: 5px; margin: 20px 0;"><h3 style="color: #1877f2; margin-top: 0;">🛠 Practical Exercise</h3><p><strong>The "Low Hanging Fruit" Check:</strong> Look for ad sets with high CPA. Turn them off. Look for ad sets with low CPA. Increase budget. You just improved results in 5 minutes.</p></div><div style="background-color: #ffffff; border: 2px solid #1877f2; padding: 20px; border-radius: 8px; margin: 20px 0;"><h3 style="color: #1877f2; margin-top: 0; text-align: center;">📝 Knowledge Check</h3><div style="margin-bottom: 15px; padding: 10px; border-bottom: 1px solid #eee;"><strong>1. Account Simplification?</strong><details><summary>Reveal</summary><p>Modern strategy: fewer campaigns, broader targeting.</p></details></div><div style="margin-bottom: 15px; padding: 10px; border-bottom: 1px solid #eee;"><strong>2. Audience Overlap?</strong><details><summary>Reveal</summary><p>Check if Ad Set A and Ad Set B are targeting the same people.</p></details></div><div style="margin-bottom: 15px; padding: 10px; border-bottom: 1px solid #eee;"><strong>3. Naming Conventions?</strong><details><summary>Reveal</summary><p>If you can''t understand what an ad set targets by reading the name, rename it.</p></details></div><div style="margin-bottom: 15px; padding: 10px; border-bottom: 1px solid #eee;"><strong>4. Change History?</strong><details><summary>Reveal</summary><p>Tool to see what the previous agency broke.</p></details></div><div style="margin-bottom: 15px; padding: 10px; border-bottom: 1px solid #eee;"><strong>5. Client Communication?</strong><details><summary>Reveal</summary><p>Report on "Business metrics" (Leads/Sales), not "Ad metrics" (CPM/CTR).</p></details></div></div>')
    ON CONFLICT (module_id, ordering) DO UPDATE SET title=EXCLUDED.title, content=EXCLUDED.content;

    INSERT INTO lessons (module_id, title, ordering, video_url, content) VALUES
    (v_mod9, 'Building a Portfolio for Freelance Work', 5, 'https://www.youtube.com/watch?v=8xM4wC7ZBmE',
    '<h2>No Experience? No Problem.</h2><p>How to get your first client.</p><p><strong>Method A: The Free Trial.</strong><br>"I will manage your ads for free for 14 days. You just pay for ad spend."</p><p><strong>Method B: The "I did it for myself"</strong><br>Run ads for your own service. Show the results.</p><div style="background-color: #ffffff; border: 2px solid #1877f2; padding: 20px; border-radius: 8px; margin: 20px 0;"><h3 style="color: #1877f2; margin-top: 0; text-align: center;">📝 Knowledge Check</h3><div style="margin-bottom: 15px; padding: 10px; border-bottom: 1px solid #eee;"><strong>1. Case Study format?</strong><details><summary>Reveal</summary><p>Problem -> Solution -> Result.</p></details></div><div style="margin-bottom: 15px; padding: 10px; border-bottom: 1px solid #eee;"><strong>2. Screenshots?</strong><details><summary>Reveal</summary><p>Always blur sensitive client info (names/IDs) in portfolio.</p></details></div><div style="margin-bottom: 15px; padding: 10px; border-bottom: 1px solid #eee;"><strong>3. Niche down?</strong><details><summary>Reveal</summary><p>"I help Gyms" is easier to sell than "I help everyone".</p></details></div><div style="margin-bottom: 15px; padding: 10px; border-bottom: 1px solid #eee;"><strong>4. Metrics to highlight?</strong><details><summary>Reveal</summary><p>ROAS and Cost Per Result. Not "Reach".</p></details></div><div style="margin-bottom: 15px; padding: 10px; border-bottom: 1px solid #eee;"><strong>5. Certifications?</strong><details><summary>Reveal</summary><p>Good for credibility, but results matter more.</p></details></div></div>')
    ON CONFLICT (module_id, ordering) DO UPDATE SET title=EXCLUDED.title, content=EXCLUDED.content;


    -- MODULE 10: CAREER & CERTIFICATION PATH
    
    INSERT INTO lessons (module_id, title, ordering, video_url, content) VALUES
    (v_mod10, 'Becoming a Facebook Ads Specialist', 1, 'https://www.youtube.com/watch?v=K53x7gaZJ2E',
    '<h2>The T-Shaped Marketer</h2><p>You need deep expertise in Ads, but broad knowledge of:</p><ul><li>Copywriting</li><li>Creative Design (Canva/Video)</li><li>Landing Page Optimization (CRO)</li><li>Data Analysis</li></ul><div style="background-color: #ffffff; border: 2px solid #1877f2; padding: 20px; border-radius: 8px; margin: 20px 0;"><h3 style="color: #1877f2; margin-top: 0; text-align: center;">📝 Knowledge Check</h3><div style="margin-bottom: 15px; padding: 10px; border-bottom: 1px solid #eee;"><strong>1. Soft skills?</strong><details><summary>Reveal</summary><p>Empathy and Communication are as important as Math.</p></details></div><div style="margin-bottom: 15px; padding: 10px; border-bottom: 1px solid #eee;"><strong>2. Daily Routine?</strong><details><summary>Reveal</summary><p>Check accounts, Analyze data, Write copy, Design creative, Report.</p></details></div><div style="margin-bottom: 15px; padding: 10px; border-bottom: 1px solid #eee;"><strong>3. Tools?</strong><details><summary>Reveal</summary><p>Ads Manager, Google Analytics, Excel/Sheets, Canva.</p></details></div><div style="margin-bottom: 15px; padding: 10px; border-bottom: 1px solid #eee;"><strong>4. Updates?</strong><details><summary>Reveal</summary><p>The platform changes weekly. Follow industry news (Jon Loomer, Social Media Examiner).</p></details></div><div style="margin-bottom: 15px; padding: 10px; border-bottom: 1px solid #eee;"><strong>5. Burnout?</strong><details><summary>Reveal</summary><p>Real risk. Set boundaries with clients.</p></details></div></div>')
    ON CONFLICT (module_id, ordering) DO UPDATE SET title=EXCLUDED.title, content=EXCLUDED.content;

    INSERT INTO lessons (module_id, title, ordering, video_url, content) VALUES
    (v_mod10, 'Freelancing vs. Agency vs. In-House', 2, 'https://www.youtube.com/watch?v=62CDBU7Hl2E',
    '<h2>Choose Your Path</h2><table style="width:100%;border-collapse:collapse;margin:20px 0;"><tr><th style="border:1px solid #ddd;padding:10px;">Path</th><th style="border:1px solid #ddd;padding:10px;">Pros</th><th style="border:1px solid #ddd;padding:10px;">Cons</th></tr><tr><td style="border:1px solid #ddd;padding:10px;">Freelancer</td><td style="border:1px solid #ddd;padding:10px;">Freedom, Max Money.</td><td style="border:1px solid #ddd;padding:10px;">Unstable. You wear all hats.</td></tr><tr><td style="border:1px solid #ddd;padding:10px;">Agency</td><td style="border:1px solid #ddd;padding:10px;">Fast learning, Team.</td><td style="border:1px solid #ddd;padding:10px;">High stress, Lower pay.</td></tr><tr><td style="border:1px solid #ddd;padding:10px;">In-House</td><td style="border:1px solid #ddd;padding:10px;">Stability, One brand focus.</td><td style="border:1px solid #ddd;padding:10px;">Slower pace, Corporate politics.</td></tr></table><div style="background-color: #ffffff; border: 2px solid #1877f2; padding: 20px; border-radius: 8px; margin: 20px 0;"><h3 style="color: #1877f2; margin-top: 0; text-align: center;">📝 Knowledge Check</h3><div style="margin-bottom: 15px; padding: 10px; border-bottom: 1px solid #eee;"><strong>1. Entry level?</strong><details><summary>Reveal</summary><p>Agency is the best place to learn fast (Trial by fire).</p></details></div><div style="margin-bottom: 15px; padding: 10px; border-bottom: 1px solid #eee;"><strong>2. Scaling freelance?</strong><details><summary>Reveal</summary><p>Hire VAs (Virtual Assistants) to handle reporting/admin.</p></details></div><div style="margin-bottom: 15px; padding: 10px; border-bottom: 1px solid #eee;"><strong>3. White Labeling?</strong><details><summary>Reveal</summary><p>Doing the work for an agency under their brand name.</p></details></div><div style="margin-bottom: 15px; padding: 10px; border-bottom: 1px solid #eee;"><strong>4. Remote work?</strong><details><summary>Reveal</summary><p>Standard in this industry.</p></details></div><div style="margin-bottom: 15px; padding: 10px; border-bottom: 1px solid #eee;"><strong>5. Job security?</strong><details><summary>Reveal</summary><p>High demand. Every business needs customers.</p></details></div></div>')
    ON CONFLICT (module_id, ordering) DO UPDATE SET title=EXCLUDED.title, content=EXCLUDED.content;

    INSERT INTO lessons (module_id, title, ordering, video_url, content) VALUES
    (v_mod10, 'Meta Blueprint Certification Prep', 3, 'https://www.youtube.com/watch?v=8xM4wC7ZBmE',
    '<h2> The Badge of Honor</h2><p>Official status from Meta.</p><ul><li><strong>410-101:</strong> Media Buying Professional (Most relevant).</li><li><strong>400-101:</strong> Digital Marketing Associate (Entry level).</li></ul><div style="background-color: #f0f8ff; border-left: 5px solid #1877f2; padding: 20px; border-radius: 5px; margin: 20px 0;"><h3 style="color: #1877f2; margin-top: 0;">🛠 Practical Exercise</h3><p><strong>Meta Blueprint:</strong> Go to facebook.com/blueprint. Take the free courses. Do not pay for the exam until you score >90% on practice tests consistently.</p></div><div style="background-color: #ffffff; border: 2px solid #1877f2; padding: 20px; border-radius: 8px; margin: 20px 0;"><h3 style="color: #1877f2; margin-top: 0; text-align: center;">📝 Knowledge Check</h3><div style="margin-bottom: 15px; padding: 10px; border-bottom: 1px solid #eee;"><strong>1. Exam Cost?</strong><details><summary>Reveal</summary><p>~$150 USD per attempt.</p></details></div><div style="margin-bottom: 15px; padding: 10px; border-bottom: 1px solid #eee;"><strong>2. Proctoring?</strong><details><summary>Reveal</summary><p>Strict. Webcam on. No looking away.</p></details></div><div style="margin-bottom: 15px; padding: 10px; border-bottom: 1px solid #eee;"><strong>3. Renewal?</strong><details><summary>Reveal</summary><p>Must renew every 1-2 years.</p></details></div><div style="margin-bottom: 15px; padding: 10px; border-bottom: 1px solid #eee;"><strong>4. Value?</strong><details><summary>Reveal</summary><p>Great for LinkedIn profile and trusting clients.</p></details></div><div style="margin-bottom: 15px; padding: 10px; border-bottom: 1px solid #eee;"><strong>5. Difficulty?</strong><details><summary>Reveal</summary><p>Harder than you think. Questions are scenario-based.</p></details></div></div>')
    ON CONFLICT (module_id, ordering) DO UPDATE SET title=EXCLUDED.title, content=EXCLUDED.content;

    INSERT INTO lessons (module_id, title, ordering, video_url, content) VALUES
    (v_mod10, 'Building Your Personal Brand', 4, 'https://www.youtube.com/watch?v=3RkBdJYUL7w',
    '<h2>Be the Expert</h2><p>People buy people.</p><p><strong>Content Pillars:</strong><br>1. Education (How-To).<br>2. Results (Case Studies).<br>3. Beliefs (Opinion/Rants).<br>4. Personal (Behind the scenes).</p><div style="background-color: #ffffff; border: 2px solid #1877f2; padding: 20px; border-radius: 8px; margin: 20px 0;"><h3 style="color: #1877f2; margin-top: 0; text-align: center;">📝 Knowledge Check</h3><div style="margin-bottom: 15px; padding: 10px; border-bottom: 1px solid #eee;"><strong>1. LinkedIn?</strong><details><summary>Reveal</summary><p>The #1 platform for B2B client acquisition.</p></details></div><div style="margin-bottom: 15px; padding: 10px; border-bottom: 1px solid #eee;"><strong>2. Newsletter?</strong><details><summary>Reveal</summary><p>Own your audience. Algorithms change.</p></details></div><div style="margin-bottom: 15px; padding: 10px; border-bottom: 1px solid #eee;"><strong>3. Consistency?</strong><details><summary>Reveal</summary><p>Post daily or weekly, but don''t stop.</p></details></div><div style="margin-bottom: 15px; padding: 10px; border-bottom: 1px solid #eee;"><strong>4. Networking?</strong><details><summary>Reveal</summary><p>Comment on other experts'' posts to gain visibility.</p></details></div><div style="margin-bottom: 15px; padding: 10px; border-bottom: 1px solid #eee;"><strong>5. Imposter Syndrome?</strong><details><summary>Reveal</summary><p>You only need to know 10% more than your client to be an expert to them.</p></details></div></div>')
    ON CONFLICT (module_id, ordering) DO UPDATE SET title=EXCLUDED.title, content=EXCLUDED.content;

    INSERT INTO lessons (module_id, title, ordering, video_url, content) VALUES
    (v_mod10, 'Landing Clients & Pricing Your Services', 5, 'https://www.youtube.com/watch?v=8xM4wC7ZBmE',
    '<h2>Getting Paid</h2><p><strong>Pricing Models:</strong></p><ul><li><strong>Retainer:</strong> Fixed fee (e.g., $1,500/month). Stable.</li><li><strong>% of Ad Spend:</strong> 15-20%. Scales as client grows.</li><li><strong>Performance:</strong> % of Profit/Revenue. Risky but high reward.</li></ul><div style="background-color: #fff3cd; border-left: 5px solid #ffc107; padding: 20px; border-radius: 5px; margin: 20px 0;"><h3 style="color: #856404; margin-top: 0;">💡 Pro Tip: The Setup Fee</h3><p>Always charge a Setup Fee (e.g., $1,000) for the first month. Building campaigns takes time.</p></div><div style="background-color: #ffffff; border: 2px solid #1877f2; padding: 20px; border-radius: 8px; margin: 20px 0;"><h3 style="color: #1877f2; margin-top: 0; text-align: center;">📝 Knowledge Check</h3><div style="margin-bottom: 15px; padding: 10px; border-bottom: 1px solid #eee;"><strong>1. Contracts?</strong><details><summary>Reveal</summary><p>Never work without one. Use a simple Service Agreement.</p></details></div><div style="margin-bottom: 15px; padding: 10px; border-bottom: 1px solid #eee;"><strong>2. Invoicing?</strong><details><summary>Reveal</summary><p>Get paid up front (at start of month).</p></details></div><div style="margin-bottom: 15px; padding: 10px; border-bottom: 1px solid #eee;"><strong>3. Reporting?</strong><details><summary>Reveal</summary><p>Send a weekly update and a monthly deep dive call.</p></details></div><div style="margin-bottom: 15px; padding: 10px; border-bottom: 1px solid #eee;"><strong>4. Firing clients?</strong><details><summary>Reveal</summary><p>If they disrespect you or pay late, fire them. You are a partner, not an employee.</p></details></div><div style="margin-bottom: 15px; padding: 10px; border-bottom: 1px solid #eee;"><strong>5. Referrals?</strong><details><summary>Reveal</summary><p>The easiest way to grow. Ask happy clients for intros.</p></details></div></div>')
    ON CONFLICT (module_id, ordering) DO UPDATE SET title=EXCLUDED.title, content=EXCLUDED.content;

END $$;
