-- FACEBOOK ADS CONTENT PART 2 (Modules 2-4)
-- GOLD STANDARD EDITION: Tables, Deep Theory, Pro Tips, Glossaries
-- Execute after FB_ADS_01_MODULE_1_FIXED.sql

DO $$
DECLARE
    v_course_id UUID := '123e4567-e89b-12d3-a456-426614174002';
    v_mod2 UUID; v_mod3 UUID; v_mod4 UUID;
BEGIN
    SELECT id INTO v_mod2 FROM modules WHERE course_id = v_course_id AND ordering = 2;
    SELECT id INTO v_mod3 FROM modules WHERE course_id = v_course_id AND ordering = 3;
    SELECT id INTO v_mod4 FROM modules WHERE course_id = v_course_id AND ordering = 4;

    -- MODULE 2: AUDIENCE & TARGETING MASTERY
    
    INSERT INTO lessons (module_id, title, ordering, video_url, content) VALUES
    (v_mod2, 'Types of Audiences: Core, Custom, Lookalike', 1, 'https://www.youtube.com/watch?v=K53x7gaZJ2E',
    '<h2>The 3 Pillars of Targeting</h2>
<p>Targeting is not just "picking interests". It is about understanding who knows you and who doesn''t.</p>

<table style="width:100%; border-collapse: collapse; margin: 20px 0;">
    <tr style="background-color: #f0f8ff;">
        <th style="padding: 10px; border: 1px solid #ddd;">Audience Type</th>
        <th style="padding: 10px; border: 1px solid #ddd;">Definition</th>
        <th style="padding: 10px; border: 1px solid #ddd;">Best Use Case</th>
    </tr>
    <tr>
        <td style="padding: 10px; border: 1px solid #ddd;"><strong>Core (Saved)</strong></td>
        <td style="padding: 10px; border: 1px solid #ddd;">Targeting based on Demographics, Interests, and Behaviors (e.g., "Golf", "Lagos", "iPhone Users").</td>
        <td style="padding: 10px; border: 1px solid #ddd;">Cold Traffic (Finding new people).</td>
    </tr>
    <tr>
        <td style="padding: 10px; border: 1px solid #ddd;"><strong>Custom</strong></td>
        <td style="padding: 10px; border: 1px solid #ddd;">People who have interacted with your business (Website visitors, Email list, Video viewers).</td>
        <td style="padding: 10px; border: 1px solid #ddd;">Retargeting (Closing the sale).</td>
    </tr>
    <tr>
        <td style="padding: 10px; border: 1px solid #ddd;"><strong>Lookalike (LAL)</strong></td>
        <td style="padding: 10px; border: 1px solid #ddd;">New people who "Look Like" your best customers.</td>
        <td style="padding: 10px; border: 1px solid #ddd;">Scaling (Finding MORE buyers efficiently).</td>
    </tr>
</table>

<div style="background-color: #f0f8ff; border-left: 5px solid #1877f2; padding: 20px; border-radius: 5px; margin: 20px 0;">
    <h3 style="color: #1877f2; margin-top: 0;">🛠 Practical Exercise</h3>
    <p><strong>Create Your First Custom Audience:</strong></p>
    <ol>
        <li>Go to <strong>Audiences</strong> in Ads Manager.</li>
        <li>Click <strong>Create Audience > Custom Audience</strong>.</li>
        <li>Select <strong>Website</strong>.</li>
        <li>Choose "All Website Visitors" (Last 30 Days).</li>
        <li>Name it: "WCA - All Visitors - 30D".</li>
    </ol>
</div>

<div style="background-color: #ffffff; border: 2px solid #1877f2; padding: 20px; border-radius: 8px; margin: 20px 0;">
    <h3 style="color: #1877f2; margin-top: 0; text-align: center;">📝 Knowledge Check</h3>
    <div style="margin-bottom: 15px; padding: 10px; border-bottom: 1px solid #eee;"><strong>1. Which audience is "Warm"?</strong><details><summary>Reveal</summary><p>Custom Audience (they know you).</p></details></div>
    <div style="margin-bottom: 15px; padding: 10px; border-bottom: 1px solid #eee;"><strong>2. To make a Lookalike, what do you need first?</strong><details><summary>Reveal</summary><p>A Source Audience (e.g., a Custom Audience of Purchasers).</p></details></div>
    <div style="margin-bottom: 15px; padding: 10px; border-bottom: 1px solid #eee;"><strong>3. Percentage ranges for LALs?</strong><details><summary>Reveal</summary><p>1% (Closest match) to 10% (Broadest match).</p></details></div>
    <div style="margin-bottom: 15px; padding: 10px; border-bottom: 1px solid #eee;"><strong>4. Can you exclude audiences?</strong><details><summary>Reveal</summary><p>Yes! Always exclude "Purchasers" from a prospecting campaign so you don''t waste money.</p></details></div>
    <div style="margin-bottom: 15px; padding: 10px; border-bottom: 1px solid #eee;"><strong>5. Flex targeting?</strong><details><summary>Reveal</summary><p>"Must match X AND Y". Example: "Parents" AND "Golfers".</p></details></div>
</div>')
    ON CONFLICT (module_id, ordering) DO UPDATE SET title=EXCLUDED.title, content=EXCLUDED.content;

    INSERT INTO lessons (module_id, title, ordering, video_url, content) VALUES
    (v_mod2, 'Building Buyer Personas', 2, 'https://www.youtube.com/watch?v=62CDBU7Hl2E',
    '<h2>Who Are You Talking To?</h2><p>If you speak to everyone, you speak to no one. You need a specific avatar.</p><h3>The Avatar Worksheet</h3><ul><li><strong>Demographics:</strong> Age, Gender, Location, Income.</li><li><strong>Psychographics:</strong> Fears, Desires, Values, Enemies.</li><li><strong>Behaviors:</strong> What phone do they use? Where do they travel?</li></ul><div style="background-color: #fff3cd; border-left: 5px solid #ffc107; padding: 20px; border-radius: 5px; margin: 20px 0;"><h3 style="color: #856404; margin-top: 0;">💡 Pro Tip: The "3 AM" Test</h3><p>What keeps your customer awake at 3 AM? Is it "I need a cheaper slightly better toaster"? No. It is "I feel like a bad mom because I don''t have time to cook breakfast." Sell to the 3 AM problem.</p></div><div style="background-color: #ffffff; border: 2px solid #1877f2; padding: 20px; border-radius: 8px; margin: 20px 0;"><h3 style="color: #1877f2; margin-top: 0; text-align: center;">📝 Knowledge Check</h3><div style="margin-bottom: 15px; padding: 10px; border-bottom: 1px solid #eee;"><strong>1. Why detail Psychographics?</strong><details><summary>Reveal</summary><p>It defines your ad copy tone and imagery.</p></details></div><div style="margin-bottom: 15px; padding: 10px; border-bottom: 1px solid #eee;"><strong>2. Negative Persona?</strong><details><summary>Reveal</summary><p>Who you DO NOT want. (e.g., Freebie seekers).</p></details></div><div style="margin-bottom: 15px; padding: 10px; border-bottom: 1px solid #eee;"><strong>3. Pain vs Pleasure?</strong><details><summary>Reveal</summary><p>Pain avoidance is usually a stronger motivator than pleasure seeking.</p></details></div><div style="margin-bottom: 15px; padding: 10px; border-bottom: 1px solid #eee;"><strong>4. Research tool?</strong><details><summary>Reveal</summary><p>Facebook Audience Insights (or Amazon Reviews of competitors).</p></details></div><div style="margin-bottom: 15px; padding: 10px; border-bottom: 1px solid #eee;"><strong>5. Niche?</strong><details><summary>Reveal</summary><p>The riches are in the niches.</p></details></div></div>')
    ON CONFLICT (module_id, ordering) DO UPDATE SET title=EXCLUDED.title, content=EXCLUDED.content;

    INSERT INTO lessons (module_id, title, ordering, video_url, content) VALUES
    (v_mod2, 'Geo, Demographic & Behavioral Targeting', 3, 'https://www.youtube.com/watch?v=8xM4wC7ZBmE',
    '<h2>Detailed Targeting</h2><p>The switches you can flip.</p><ul><li><strong>Location:</strong> "People living in" vs "People recently in".</li><li><strong>Demographics:</strong> Education, Life Events (Newly Engaged, Birthday), Work.</li><li><strong>Behaviors:</strong> Digital Activities, Travel, Purchase Behavior.</li></ul><div style="background-color: #f0f8ff; border-left: 5px solid #1877f2; padding: 20px; border-radius: 5px; margin: 20px 0;"><h3 style="color: #1877f2; margin-top: 0;">🛠 Practical Exercise</h3><p><strong>Find the "Expats":</strong> Go to Detailed Targeting > Behaviors > Expats. You can target "Expats (Nigeria)" living in "United States" to sell remittance services or cultural goods.</p></div><div style="background-color: #ffffff; border: 2px solid #1877f2; padding: 20px; border-radius: 8px; margin: 20px 0;"><h3 style="color: #1877f2; margin-top: 0; text-align: center;">📝 Knowledge Check</h3><div style="margin-bottom: 15px; padding: 10px; border-bottom: 1px solid #eee;"><strong>1. Relationship Status?</strong><details><summary>Reveal</summary><p>Target "Engaged" for Wedding photographers.</p></details></div><div style="margin-bottom: 15px; padding: 10px; border-bottom: 1px solid #eee;"><strong>2. Mobile Device User?</strong><details><summary>Reveal</summary><p>Target "Access Facebook (Mobile): iPhone X" for phone cases.</p></details></div><div style="margin-bottom: 15px; padding: 10px; border-bottom: 1px solid #eee;"><strong>3. Parents?</strong><details><summary>Reveal</summary><p>Can target by child age (e.g., Parents with toddlers 1-2 years).</p></details></div><div style="margin-bottom: 15px; padding: 10px; border-bottom: 1px solid #eee;"><strong>4. Birthday?</strong><details><summary>Reveal</summary><p>Target "Upcoming Birthday" with a special offer.</p></details></div><div style="margin-bottom: 15px; padding: 10px; border-bottom: 1px solid #eee;"><strong>5. Drop Pin targeting?</strong><details><summary>Reveal</summary><p>Targeting a specific 1-mile radius around a physical store.</p></details></div></div>')
    ON CONFLICT (module_id, ordering) DO UPDATE SET title=EXCLUDED.title, content=EXCLUDED.content;

    INSERT INTO lessons (module_id, title, ordering, video_url, content) VALUES
    (v_mod2, 'Retargeting Strategies', 4, 'https://www.youtube.com/watch?v=3RkBdJYUL7w',
    '<h2>The Money Is In The Follow-Up</h2><p>Most people don''t buy on the first visit. Retargeting brings them back.</p><h3>Classic Retargeting Flows</h3><ul><li><strong>Generic:</strong> "Come back."</li><li><strong>Dynamic:</strong> "You looked at these shoes. Here they are again."</li><li><strong>Testimonial:</strong> "Here is what others say."</li></ul><div style="background-color: #f8d7da; border-left: 5px solid #dc3545; padding: 20px; border-radius: 5px; margin: 20px 0;"><h3 style="color: #721c24; margin-top: 0;">🚨 WARNING: Frequency</h3><p>Retargeting audiences are small. If you put a huge budget, you will bombard them 20 times a day. Keep frequency under 3-4.</p></div><div style="background-color: #ffffff; border: 2px solid #1877f2; padding: 20px; border-radius: 8px; margin: 20px 0;"><h3 style="color: #1877f2; margin-top: 0; text-align: center;">📝 Knowledge Check</h3><div style="margin-bottom: 15px; padding: 10px; border-bottom: 1px solid #eee;"><strong>1. Content interactions?</strong><details><summary>Reveal</summary><p>Retarget people who watched 50% of your video.</p></details></div><div style="margin-bottom: 15px; padding: 10px; border-bottom: 1px solid #eee;"><strong>2. The Timeframe?</strong><details><summary>Reveal</summary><p>Hot (3 Days), Warm (30 Days), Cool (180 Days).</p></details></div><div style="margin-bottom: 15px; padding: 10px; border-bottom: 1px solid #eee;"><strong>3. Offer?</strong><details><summary>Reveal</summary><p>Add urgency or a discount code in retargeting.</p></details></div><div style="margin-bottom: 15px; padding: 10px; border-bottom: 1px solid #eee;"><strong>4. Exclusion?</strong><details><summary>Reveal</summary><p>Exclude Purchasers!</p></details></div><div style="margin-bottom: 15px; padding: 10px; border-bottom: 1px solid #eee;"><strong>5. Cross-sell?</strong><details><summary>Reveal</summary><p>Target Purchasers suggesting a complementary product.</p></details></div></div>')
    ON CONFLICT (module_id, ordering) DO UPDATE SET title=EXCLUDED.title, content=EXCLUDED.content;

    INSERT INTO lessons (module_id, title, ordering, video_url, content) VALUES
    (v_mod2, 'Audience Layering for Precision', 5, 'https://www.youtube.com/watch?v=K53x7gaZJ2E',
    '<h2>Sniper Targeting</h2><p>Combining criteria to find the perfect match.</p><p><strong>Formula:</strong> Audience = [Location] AND [Identity] AND [Interest]</p><div style="background-color: #f0f8ff; border-left: 5px solid #1877f2; padding: 20px; border-radius: 5px; margin: 20px 0;"><h3 style="color: #1877f2; margin-top: 0;">🛠 Practical Exercise</h3><p><strong>Narrow Audience:</strong> Create an audience for "Luxury Watch Buyers".<br>1. Interest: "Rolex" (Too broad).<br>2. Click "Narrow Audience".<br>3. Behavior: "Frequent International Travelers".<br>4. Now you have Rich People who like Rolex.</p></div><div style="background-color: #ffffff; border: 2px solid #1877f2; padding: 20px; border-radius: 8px; margin: 20px 0;"><h3 style="color: #1877f2; margin-top: 0; text-align: center;">📝 Knowledge Check</h3><div style="margin-bottom: 15px; padding: 10px; border-bottom: 1px solid #eee;"><strong>1. OR logic?</strong><details><summary>Reveal</summary><p>Include "Golf" OR "Tennis". (Broadens Audience).</p></details></div><div style="margin-bottom: 15px; padding: 10px; border-bottom: 1px solid #eee;"><strong>2. AND logic?</strong><details><summary>Reveal</summary><p>Include "Golf" AND "Tennis". (Narrows Audience).</p></details></div><div style="margin-bottom: 15px; padding: 10px; border-bottom: 1px solid #eee;"><strong>3. Expanding Interest?</strong><details><summary>Reveal</summary><p>The checkbox "Reach people beyond your detailed targeting". Avoid for strict testing.</p></details></div><div style="margin-bottom: 15px; padding: 10px; border-bottom: 1px solid #eee;"><strong>4. Audience Size?</strong><details><summary>Reveal</summary><p>Too small (<100k) is bad for CPM. Too big (>10M) needs big budget.</p></details></div><div style="margin-bottom: 15px; padding: 10px; border-bottom: 1px solid #eee;"><strong>5. Overlapping?</strong><details><summary>Reveal</summary><p>Be careful not to layer too much or you wind up with 0 people.</p></details></div></div>')
    ON CONFLICT (module_id, ordering) DO UPDATE SET title=EXCLUDED.title, content=EXCLUDED.content;


    -- MODULE 3: CAMPAIGN STRATEGY & OBJECTIVES
    
    INSERT INTO lessons (module_id, title, ordering, video_url, content) VALUES
    (v_mod3, 'Choosing the Right Campaign Objective', 1, 'https://www.youtube.com/watch?v=62CDBU7Hl2E',
    '<h2>Tell Facebook What You Want</h2><p>Facebook is literal. You get what you ask for.</p><table style="width:100%;border-collapse:collapse;margin:20px 0;"><tr><th style="border:1px solid #ddd;padding:10px;">Objective</th><th style="border:1px solid #ddd;padding:10px;">Result</th></tr><tr><td style="border:1px solid #ddd;padding:10px;">Awareness</td><td style="border:1px solid #ddd;padding:10px;">Views (Cheap, no sales).</td></tr><tr><td style="border:1px solid #ddd;padding:10px;">Traffic</td><td style="border:1px solid #ddd;padding:10px;">Clicks (Ghost visitors).</td></tr><tr><td style="border:1px solid #ddd;padding:10px;">Sales</td><td style="border:1px solid #ddd;padding:10px;">Purchases (Expensive but valuable).</td></tr></table><div style="background-color: #fff3cd; border-left: 5px solid #ffc107; padding: 20px; border-radius: 5px; margin: 20px 0;"><h3 style="color: #856404; margin-top: 0;">💡 Pro Tip</h3><p>Don''t run "Traffic" ads expecting "Sales". Facebook will find people who click links but never buy. If you want Sales, choose Sales.</p></div><div style="background-color: #ffffff; border: 2px solid #1877f2; padding: 20px; border-radius: 8px; margin: 20px 0;"><h3 style="color: #1877f2; margin-top: 0; text-align: center;">📝 Knowledge Check</h3><div style="margin-bottom: 15px; padding: 10px; border-bottom: 1px solid #eee;"><strong>1. Lead Gen objective?</strong><details><summary>Reveal</summary><p>Uses Instant Forms inside Facebook.</p></details></div><div style="margin-bottom: 15px; padding: 10px; border-bottom: 1px solid #eee;"><strong>2. Engagement objective?</strong><details><summary>Reveal</summary><p>Likes, Comments, Shares, Video Views.</p></details></div><div style="margin-bottom: 15px; padding: 10px; border-bottom: 1px solid #eee;"><strong>3. App Promotion?</strong><details><summary>Reveal</summary><p>Installs.</p></details></div><div style="margin-bottom: 15px; padding: 10px; border-bottom: 1px solid #eee;"><strong>4. What is ODAO?</strong><details><summary>Reveal</summary><p>Outcome-Driven Ad Optimization.</p></details></div><div style="margin-bottom: 15px; padding: 10px; border-bottom: 1px solid #eee;"><strong>5. Choosing wrong?</strong><details><summary>Reveal</summary><p>The #1 reason campaigns fail.</p></details></div></div>')
    ON CONFLICT (module_id, ordering) DO UPDATE SET title=EXCLUDED.title, content=EXCLUDED.content;

    INSERT INTO lessons (module_id, title, ordering, video_url, content) VALUES
    (v_mod3, 'Awareness vs. Consideration vs. Conversion', 2, 'https://www.youtube.com/watch?v=8xM4wC7ZBmE',
    '<h2>The Funnel Stages</h2><p>Aligning your objective with the customer journey.</p><ul><li><strong>Top of Funnel (TOFU):</strong> Awareness. "I have a problem."</li><li><strong>Middle of Funnel (MOFU):</strong> Consideration. "You are an option."</li><li><strong>Bottom of Funnel (BOFU):</strong> Conversion. "I am buying."</li></ul><div style="background-color: #ffffff; border: 2px solid #1877f2; padding: 20px; border-radius: 8px; margin: 20px 0;"><h3 style="color: #1877f2; margin-top: 0; text-align: center;">📝 Knowledge Check</h3><div style="margin-bottom: 15px; padding: 10px; border-bottom: 1px solid #eee;"><strong>1. Video Views?</strong><details><summary>Reveal</summary><p>Usually Consideration.</p></details></div><div style="margin-bottom: 15px; padding: 10px; border-bottom: 1px solid #eee;"><strong>2. Reach vs Brand Awareness?</strong><details><summary>Reveal</summary><p>Reach = Maximize people. Brand Awareness = Maximize recall.</p></details></div><div style="margin-bottom: 15px; padding: 10px; border-bottom: 1px solid #eee;"><strong>3. Catalog Sales?</strong><details><summary>Reveal</summary><p>Conversion (Dynamic Ads).</p></details></div><div style="margin-bottom: 15px; padding: 10px; border-bottom: 1px solid #eee;"><strong>4. Store Traffic?</strong><details><summary>Reveal</summary><p>Conversion (Physical).</p></details></div><div style="margin-bottom: 15px; padding: 10px; border-bottom: 1px solid #eee;"><strong>5. Messages?</strong><details><summary>Reveal</summary><p>Can be Consideration or Conversion.</p></details></div></div>')
    ON CONFLICT (module_id, ordering) DO UPDATE SET title=EXCLUDED.title, content=EXCLUDED.content;

    INSERT INTO lessons (module_id, title, ordering, video_url, content) VALUES
    (v_mod3, 'Funnel Mapping with Facebook Ads', 3, 'https://www.youtube.com/watch?v=3RkBdJYUL7w',
    '<h2>Visualizing the Path</h2><p>Don''t just run ads. Build a system.</p><p><strong>Example Strategy:</strong><br>1. Video Ad (Awareness) -> Watch 50%.<br>2. Retarget 50% watchers with Testimonial Ad (Consideration) -> Click.<br>3. Retarget Website Visitors with Discount (Conversion) -> Buy.</p><div style="background-color: #f0f8ff; border-left: 5px solid #1877f2; padding: 20px; border-radius: 5px; margin: 20px 0;"><h3 style="color: #1877f2; margin-top: 0; text-align: center;">🛠 Practical Exercise</h3><p><strong>Draw Your Funnel:</strong> Take a piece of paper. Draw 3 boxes (Ad 1, Ad 2, Ad 3). Define the Audience and Objective for each.</p></div><div style="background-color: #ffffff; border: 2px solid #1877f2; padding: 20px; border-radius: 8px; margin: 20px 0;"><h3 style="color: #1877f2; margin-top: 0; text-align: center;">📝 Knowledge Check</h3><div style="margin-bottom: 15px; padding: 10px; border-bottom: 1px solid #eee;"><strong>1. Leaky Funnel?</strong><details><summary>Reveal</summary><p>Losing people between steps (e.g., Clicked but didn''t load page).</p></details></div><div style="margin-bottom: 15px; padding: 10px; border-bottom: 1px solid #eee;"><strong>2. Upsell?</strong><details><summary>Reveal</summary><p>Offering more after the purchase.</p></details></div><div style="margin-bottom: 15px; padding: 10px; border-bottom: 1px solid #eee;"><strong>3. One-step funnel?</strong><details><summary>Reveal</summary><p>Direct to Offer. Works for low ticket items.</p></details></div><div style="margin-bottom: 15px; padding: 10px; border-bottom: 1px solid #eee;"><strong>4. Lead Magnet?</strong><details><summary>Reveal</summary><p>Free item (PDF) given in exchange for email.</p></details></div><div style="margin-bottom: 15px; padding: 10px; border-bottom: 1px solid #eee;"><strong>5. Tripwire?</strong><details><summary>Reveal</summary><p>Low cost product ($7) to turn a lead into a customer.</p></details></div></div>')
    ON CONFLICT (module_id, ordering) DO UPDATE SET title=EXCLUDED.title, content=EXCLUDED.content;

    INSERT INTO lessons (module_id, title, ordering, video_url, content) VALUES
    (v_mod3, 'Budgeting: Daily vs. Lifetime', 4, 'https://www.youtube.com/watch?v=K53x7gaZJ2E',
    '<h2>Spending Your Money</h2><p>Two ways to pay.</p><table style="width:100%;border-collapse:collapse;margin:20px 0;"><tr><th style="border:1px solid #ddd;padding:10px;">Type</th><th style="border:1px solid #ddd;padding:10px;">Pros</th><th style="border:1px solid #ddd;padding:10px;">Cons</th></tr><tr><td style="border:1px solid #ddd;padding:10px;">Daily</td><td style="border:1px solid #ddd;padding:10px;">Consistency. Good for ongoing campaigns.</td><td style="border:1px solid #ddd;padding:10px;">Will spend even on bad days.</td></tr><tr><td style="border:1px solid #ddd;padding:10px;">Lifetime</td><td style="border:1px solid #ddd;padding:10px;">Allows "Dayparting" (Scheduling).</td><td style="border:1px solid #ddd;padding:10px;">Hard to scale accurately. pacing issues.</td></tr></table><div style="background-color: #ffffff; border: 2px solid #1877f2; padding: 20px; border-radius: 8px; margin: 20px 0;"><h3 style="color: #1877f2; margin-top: 0; text-align: center;">📝 Knowledge Check</h3><div style="margin-bottom: 15px; padding: 10px; border-bottom: 1px solid #eee;"><strong>1. Dayparting?</strong><details><summary>Reveal</summary><p>Running ads only at specific times (e.g., 9am-5pm). Only possible with Lifetime Budget.</p></details></div><div style="margin-bottom: 15px; padding: 10px; border-bottom: 1px solid #eee;"><strong>2. Pacing?</strong><details><summary>Reveal</summary><p>How Facebook distributes spending over time.</p></details></div><div style="margin-bottom: 15px; padding: 10px; border-bottom: 1px solid #eee;"><strong>3. Changing budget?</strong><details><summary>Reveal</summary><p>Big changes (50%+) reset the Learning Phase.</p></details></div><div style="margin-bottom: 15px; padding: 10px; border-bottom: 1px solid #eee;"><strong>4. Minimum budget?</strong><details><summary>Reveal</summary><p>Usually $1/day (or equivalent in NGN) per ad set.</p></details></div><div style="margin-bottom: 15px; padding: 10px; border-bottom: 1px solid #eee;"><strong>5. Sales peaks?</strong><details><summary>Reveal</summary><p>Weekends vs Weekdays vary by industry.</p></details></div></div>')
    ON CONFLICT (module_id, ordering) DO UPDATE SET title=EXCLUDED.title, content=EXCLUDED.content;

    INSERT INTO lessons (module_id, title, ordering, video_url, content) VALUES
    (v_mod3, 'Bidding Strategies & Optimization', 5, 'https://www.youtube.com/watch?v=62CDBU7Hl2E',
    '<h2>How to Bid</h2><p>Controlling cost vs volume.</p><ul><li><strong>Lowest Cost (Auto):</strong> Get most results for budget. (Recommended for beginners).</li><li><strong>Cost Cap:</strong> "Don''t spend more than $5 per Lead".</li><li><strong>Bid Cap:</strong> "Count bid $2 in the auction".</li></ul><div style="background-color: #ffffff; border: 2px solid #1877f2; padding: 20px; border-radius: 8px; margin: 20px 0;"><h3 style="color: #1877f2; margin-top: 0; text-align: center;">📝 Knowledge Check</h3><div style="margin-bottom: 15px; padding: 10px; border-bottom: 1px solid #eee;"><strong>1. Risk of Cost Cap?</strong><details><summary>Reveal</summary><p>If cap is too low, ad won''t spend at all.</p></details></div><div style="margin-bottom: 15px; padding: 10px; border-bottom: 1px solid #eee;"><strong>2. ROAS Goal?</strong><details><summary>Reveal</summary><p>Tell Facebook to aim for a specific return (e.g., 2.0).</p></details></div><div style="margin-bottom: 15px; padding: 10px; border-bottom: 1px solid #eee;"><strong>3. Accelerated Delivery?</strong><details><summary>Reveal</summary><p>Spend money as fast as possible (Manual bid only).</p></details></div><div style="margin-bottom: 15px; padding: 10px; border-bottom: 1px solid #eee;"><strong>4. Conversion Window?</strong><details><summary>Reveal</summary><p>7-day click or 1-day view. Tells Facebook how long to wait to count a sale.</p></details></div><div style="margin-bottom: 15px; padding: 10px; border-bottom: 1px solid #eee;"><strong>5. Highest Volume?</strong><details><summary>Reveal</summary><p>Another name for Lowest Cost.</p></details></div></div>')
    ON CONFLICT (module_id, ordering) DO UPDATE SET title=EXCLUDED.title, content=EXCLUDED.content;


    -- MODULE 4: CREATIVE THAT CONVERTS
    
    INSERT INTO lessons (module_id, title, ordering, video_url, content) VALUES
    (v_mod4, 'Ad Formats: Image, Video, Carousel, Collection', 1, 'https://www.youtube.com/watch?v=8xM4wC7ZBmE',
    '<h2>The Canvas</h2><p>Different stories require different formats.</p><ul><li><strong>Single Image:</strong> Simple, direct. Good for traffic.</li><li><strong>Video:</strong> King of engagement. Critical for storytelling.</li><li><strong>Carousel:</strong> Multiple cards. Great for e-commerce products or "Step-by-Step".</li><li><strong>Collection:</strong> Instant Experience (Mobile landing page).</li></ul><div style="background-color: #f0f8ff; border-left: 5px solid #1877f2; padding: 20px; border-radius: 5px; margin: 20px 0;"><h3 style="color: #1877f2; margin-top: 0;">🛠 Practical Exercise</h3><p><strong>Carousel Story:</strong> Draft a 3-card carousel.<br>Card 1: The Problem.<br>Card 2: The Solution (Your Product).<br>Card 3: Testimonial/Result.</p></div><div style="background-color: #ffffff; border: 2px solid #1877f2; padding: 20px; border-radius: 8px; margin: 20px 0;"><h3 style="color: #1877f2; margin-top: 0; text-align: center;">📝 Knowledge Check</h3><div style="margin-bottom: 15px; padding: 10px; border-bottom: 1px solid #eee;"><strong>1. 1:1 vs 9:16?</strong><details><summary>Reveal</summary><p>Square (1:1) for Feed. Vertical (9:16) for Stories/Reels.</p></details></div><div style="margin-bottom: 15px; padding: 10px; border-bottom: 1px solid #eee;"><strong>2. 20% Text Rule?</strong><details><summary>Reveal</summary><p>Old rule, but valid principle. Too much text on image reduces reach.</p></details></div><div style="margin-bottom: 15px; padding: 10px; border-bottom: 1px solid #eee;"><strong>3. Collection Load Speed?</strong><details><summary>Reveal</summary><p>Instant. Hosted on Facebook servers.</p></details></div><div style="margin-bottom: 15px; padding: 10px; border-bottom: 1px solid #eee;"><strong>4. Slideshow?</strong><details><summary>Reveal</summary><p>Turning images into a video. Lightweight alternative to filming.</p></details></div><div style="margin-bottom: 15px; padding: 10px; border-bottom: 1px solid #eee;"><strong>5. Aspect Ratio?</strong><details><summary>Reveal</summary><p>Use 4:5 for Feed to take up more vertical screen space than 1:1.</p></details></div></div>')
    ON CONFLICT (module_id, ordering) DO UPDATE SET title=EXCLUDED.title, content=EXCLUDED.content;

    INSERT INTO lessons (module_id, title, ordering, video_url, content) VALUES
    (v_mod4, 'Writing High-Converting Ad Copy', 2, 'https://www.youtube.com/watch?v=3RkBdJYUL7w',
    '<h2>Words That Sell</h2><p>copywriting is salesmanship in print.</p><h3>The AIDA Framework</h3><ul><li><strong>Attention:</strong> Stop the scroll (Headline).</li><li><strong>Interest:</strong> Engage the brain.</li><li><strong>Desire:</strong> Emotional connection.</li><li><strong>Action:</strong> Click the button.</li></ul><div style="background-color: #fff3cd; border-left: 5px solid #ffc107; padding: 20px; border-radius: 5px; margin: 20px 0;"><h3 style="color: #856404; margin-top: 0;">💡 Pro Tip: The "See More" Button</h3><p>Your first 2 lines are the most important. If they don''t compel value, nobody clicks "See More" to read the rest.</p></div><div style="background-color: #ffffff; border: 2px solid #1877f2; padding: 20px; border-radius: 8px; margin: 20px 0;"><h3 style="color: #1877f2; margin-top: 0; text-align: center;">📝 Knowledge Check</h3><div style="margin-bottom: 15px; padding: 10px; border-bottom: 1px solid #eee;"><strong>1. Short vs Long copy?</strong><details><summary>Reveal</summary><p>Test both. Long copy educates (Consideration). Short copy punches (Brand).</p></details></div><div style="margin-bottom: 15px; padding: 10px; border-bottom: 1px solid #eee;"><strong>2. Headline location?</strong><details><summary>Reveal</summary><p>Appears BELOW the image in big bold text.</p></details></div><div style="margin-bottom: 15px; padding: 10px; border-bottom: 1px solid #eee;"><strong>3. Primary Text?</strong><details><summary>Reveal</summary><p>The caption above the image.</p></details></div><div style="margin-bottom: 15px; padding: 10px; border-bottom: 1px solid #eee;"><strong>4. Emojis?</strong><details><summary>Reveal</summary><p>Use them Use them as bullet points or emotional cues. Don''t overdo it.</p></details></div><div style="margin-bottom: 15px; padding: 10px; border-bottom: 1px solid #eee;"><strong>5. Call to Action (CTA)?</strong><details><summary>Reveal</summary><p>"Learn More" usually converts better than "Shop Now" (less aggressive).</p></details></div></div>')
    ON CONFLICT (module_id, ordering) DO UPDATE SET title=EXCLUDED.title, content=EXCLUDED.content;

    INSERT INTO lessons (module_id, title, ordering, video_url, content) VALUES
    (v_mod4, 'Visual Psychology & Design Principles', 3, 'https://www.youtube.com/watch?v=K53x7gaZJ2E',
    '<h2>Stopping Power</h2><p>Design for the subconscious.</p><ul><li><strong>Contrast:</strong> Make it pop against the white/dark Facebook background.</li><li><strong>Faces:</strong> Humans look at eyes. Use eyes to point at your headline.</li><li><strong>Native Feel:</strong> Sometimes "Ugly" ads work best because they look like user content (UGC).</li></ul><div style="background-color: #ffffff; border: 2px solid #1877f2; padding: 20px; border-radius: 8px; margin: 20px 0;"><h3 style="color: #1877f2; margin-top: 0; text-align: center;">📝 Knowledge Check</h3><div style="margin-bottom: 15px; padding: 10px; border-bottom: 1px solid #eee;"><strong>1. Pattern Interrupt?</strong><details><summary>Reveal</summary><p>Something unexpected that breaks the scrolling hypnosis.</p></details></div><div style="margin-bottom: 15px; padding: 10px; border-bottom: 1px solid #eee;"><strong>2. Color Psychology?</strong><details><summary>Reveal</summary><p>Red = Urgency. Blue = Trust. Orange = Cheap/Value.</p></details></div><div style="margin-bottom: 15px; padding: 10px; border-bottom: 1px solid #eee;"><strong>3. Typography?</strong><details><summary>Reveal</summary><p>Keep it readable. Sans-serif fonts are best for mobile.</p></details></div><div style="margin-bottom: 15px; padding: 10px; border-bottom: 1px solid #eee;"><strong>4. Thumbnail?</strong><details><summary>Reveal</summary><p>Critical for video. If the thumbnail is boring, play rate is 0.</p></details></div><div style="margin-bottom: 15px; padding: 10px; border-bottom: 1px solid #eee;"><strong>5. Motion?</strong><details><summary>Reveal</summary><p>Movement captures the eye faster than static.</p></details></div></div>')
    ON CONFLICT (module_id, ordering) DO UPDATE SET title=EXCLUDED.title, content=EXCLUDED.content;

    INSERT INTO lessons (module_id, title, ordering, video_url, content) VALUES
    (v_mod4, 'A/B Testing Creatives', 4, 'https://www.youtube.com/watch?v=62CDBU7Hl2E',
    '<h2>The Scientific Method</h2><p>Never guess. Test.</p><p><strong>The Variable Rule:</strong> Only change ONE thing at a time. If you change the Image AND the Headline, you won''t know which one caused the improvement.</p><div style="background-color: #f0f8ff; border-left: 5px solid #1877f2; padding: 20px; border-radius: 5px; margin: 20px 0;"><h3 style="color: #1877f2; margin-top: 0;">🛠 Practical Exercise</h3><p><strong>The 3-Hook Test:</strong> Create 1 video. Create 3 different first 3-seconds (Hooks). Run them as 3 separate ads. The winner is your Scaler.</p></div><div style="background-color: #ffffff; border: 2px solid #1877f2; padding: 20px; border-radius: 8px; margin: 20px 0;"><h3 style="color: #1877f2; margin-top: 0; text-align: center;">📝 Knowledge Check</h3><div style="margin-bottom: 15px; padding: 10px; border-bottom: 1px solid #eee;"><strong>1. Statistical Significance?</strong><details><summary>Reveal</summary><p>Do you have enough data to be sure it wasn''t luck? (Need ~50 conversions).</p></details></div><div style="margin-bottom: 15px; padding: 10px; border-bottom: 1px solid #eee;"><strong>2. Creative Fatigue?</strong><details><summary>Reveal</summary><p>When a winning ad stops working because everyone has seen it.</p></details></div><div style="margin-bottom: 15px; padding: 10px; border-bottom: 1px solid #eee;"><strong>3. Iteration?</strong><details><summary>Reveal</summary><p>Taking the winner and trying to beat it.</p></details></div><div style="margin-bottom: 15px; padding: 10px; border-bottom: 1px solid #eee;"><strong>4. Split Test feature?</strong><details><summary>Reveal</summary><p>Facebook''s built-in tool to ensure audiences don''t overlap during tests.</p></details></div><div style="margin-bottom: 15px; padding: 10px; border-bottom: 1px solid #eee;"><strong>5. Budget allocation?</strong><details><summary>Reveal</summary><p>Spend 10-20% of budget on testing, 80% on winners.</p></details></div></div>')
    ON CONFLICT (module_id, ordering) DO UPDATE SET title=EXCLUDED.title, content=EXCLUDED.content;

    INSERT INTO lessons (module_id, title, ordering, video_url, content) VALUES
    (v_mod4, 'Using Dynamic Creative Optimization', 5, 'https://www.youtube.com/watch?v=8xM4wC7ZBmE',
    '<h2>Let the Machine Decide</h2><p>DCO (Dynamic Creative Optimization) allows you to upload 5 images, 5 headlines, and 5 descriptions. Facebook mixes and matches them to find the perfect combo for each user.</p><div style="background-color: #ffffff; border: 2px solid #1877f2; padding: 20px; border-radius: 8px; margin: 20px 0;"><h3 style="color: #1877f2; margin-top: 0; text-align: center;">📝 Knowledge Check</h3><div style="margin-bottom: 15px; padding: 10px; border-bottom: 1px solid #eee;"><strong>1. Benefits of DCO?</strong><details><summary>Reveal</summary><p>Automation and personalization. Saves time setting up manual tests.</p></details></div><div style="margin-bottom: 15px; padding: 10px; border-bottom: 1px solid #eee;"><strong>2. Downsides?</strong><details><summary>Reveal</summary><p>Analyzing results is harder. You see the total, not the specific breakdown easily.</p></details></div><div style="margin-bottom: 15px; padding: 10px; border-bottom: 1px solid #eee;"><strong>3. 3:2:2 Method?</strong><details><summary>Reveal</summary><p>A popular DCO strategy: 3 Creatives, 2 Primary Texts, 2 Headlines.</p></details></div><div style="margin-bottom: 15px; padding: 10px; border-bottom: 1px solid #eee;"><strong>4. Placement customization?</strong><details><summary>Reveal</summary><p>You can crop images differently for Stories vs Feed within DCO.</p></details></div><div style="margin-bottom: 15px; padding: 10px; border-bottom: 1px solid #eee;"><strong>5. When to use?</strong><details><summary>Reveal</summary><p>Great for initial testing.</p></details></div></div>')
    ON CONFLICT (module_id, ordering) DO UPDATE SET title=EXCLUDED.title, content=EXCLUDED.content;

END $$;
