-- FACEBOOK ADS CONTENT PART 3 (Modules 5-7)
-- GOLD STANDARD EDITION: Tables, Deep Theory, Pro Tips
-- Execute after FB_ADS_01_MODULE_1_FIXED.sql

DO $$
DECLARE
    v_course_id UUID := '123e4567-e89b-12d3-a456-426614174002';
    v_mod5 UUID; v_mod6 UUID; v_mod7 UUID;
BEGIN
    SELECT id INTO v_mod5 FROM modules WHERE course_id = v_course_id AND ordering = 5;
    SELECT id INTO v_mod6 FROM modules WHERE course_id = v_course_id AND ordering = 6;
    SELECT id INTO v_mod7 FROM modules WHERE course_id = v_course_id AND ordering = 7;

    -- MODULE 5: PIXEL, EVENTS & TRACKING
    
    INSERT INTO lessons (module_id, title, ordering, video_url, content) VALUES
    (v_mod5, 'Installing the Facebook Pixel', 1, 'https://www.youtube.com/watch?v=8xM4wC7ZBmE',
    '<h2>The Brain of Your Operation</h2><p>Without the Pixel, you are flying blind.</p><p>The Meta Pixel is a piece of code that you place on your website. It reports back to Facebook: "Hey! John just bought a red shirt for $50."</p><div style="background-color: #f0f8ff; border-left: 5px solid #1877f2; padding: 20px; border-radius: 5px; margin: 20px 0;"><h3 style="color: #1877f2; margin-top: 0;">🛠 Practical Exercise</h3><p><strong>Pixel Audit:</strong><br>1. Install the <strong>"Meta Pixel Helper"</strong> Chrome Extension.<br>2. Visit your website.<br>3. Click the extension icon.<br>4. Green Checkmark? You are good. No Pixel found? You exist in 1999.</p></div><div style="background-color: #ffffff; border: 2px solid #1877f2; padding: 20px; border-radius: 8px; margin: 20px 0;"><h3 style="color: #1877f2; margin-top: 0; text-align: center;">📝 Knowledge Check</h3><div style="margin-bottom: 15px; padding: 10px; border-bottom: 1px solid #eee;"><strong>1. Where does the code go?</strong><details><summary>Reveal</summary><p>Between the &lt;head&gt; tags of your website code (on every page).</p></details></div><div style="margin-bottom: 15px; padding: 10px; border-bottom: 1px solid #eee;"><strong>2. Pixel ID?</strong><details><summary>Reveal</summary><p>Your unique tracking number. Keep it secret.</p></details></div><div style="margin-bottom: 15px; padding: 10px; border-bottom: 1px solid #eee;"><strong>3. One Pixel or Many?</strong><details><summary>Reveal</summary><p>One Pixel per Domain/Business is best practice to consolidate data.</p></details></div><div style="margin-bottom: 15px; padding: 10px; border-bottom: 1px solid #eee;"><strong>4. Matching Advanced?</strong><details><summary>Reveal</summary><p>Turning on "Automatic Advanced Matching" lets Facebook use email/phone data to match visitors.</p></details></div><div style="margin-bottom: 15px; padding: 10px; border-bottom: 1px solid #eee;"><strong>5. Permissions?</strong><details><summary>Reveal</summary><p>With iOS 14, users can block tracking. The Pixel is less effective than it used to be (Enter: CAPI).</p></details></div></div>')
    ON CONFLICT (module_id, ordering) DO UPDATE SET title=EXCLUDED.title, content=EXCLUDED.content;

    INSERT INTO lessons (module_id, title, ordering, video_url, content) VALUES
    (v_mod5, 'Standard vs. Custom Events', 2, 'https://www.youtube.com/watch?v=K53x7gaZJ2E',
    '<h2>Speaking the Language</h2><p>You need to tell Facebook exactly what happened.</p><table style="width:100%;border-collapse:collapse;margin:20px 0;"><tr><th style="border:1px solid #ddd;padding:10px;">Event Type</th><th style="border:1px solid #ddd;padding:10px;">Examples</th><th style="border:1px solid #ddd;padding:10px;">Benefit</th></tr><tr><td style="border:1px solid #ddd;padding:10px;">Standard</td><td style="border:1px solid #ddd;padding:10px;">Purchase, Lead, AddToCart.</td><td style="border:1px solid #ddd;padding:10px;">Facebook understands these globally. Better optimization.</td></tr><tr><td style="border:1px solid #ddd;padding:10px;">Custom</td><td style="border:1px solid #ddd;padding:10px;">"Scrolled 50%", "Clicked Yellow Button".</td><td style="border:1px solid #ddd;padding:10px;">Specific to YOUR business logic.</td></tr></table><div style="background-color: #fff3cd; border-left: 5px solid #ffc107; padding: 20px; border-radius: 5px; margin: 20px 0;"><h3 style="color: #856404; margin-top: 0;">💡 Pro Tip</h3><p>Always prioritize <strong>Standard Events</strong>. Facebook''s AI is trained on trillions of "Purchase" events. It knows what a buyer looks like. It does NOT know what a "Clicked Yellow Button" person looks like.</p></div><div style="background-color: #ffffff; border: 2px solid #1877f2; padding: 20px; border-radius: 8px; margin: 20px 0;"><h3 style="color: #1877f2; margin-top: 0; text-align: center;">📝 Knowledge Check</h3><div style="margin-bottom: 15px; padding: 10px; border-bottom: 1px solid #eee;"><strong>1. Parameters?</strong><details><summary>Reveal</summary><p>Extra info sent with event (e.g., Value: $50.00, Currency: USD).</p></details></div><div style="margin-bottom: 15px; padding: 10px; border-bottom: 1px solid #eee;"><strong>2. Custom Conversion?</strong><details><summary>Reveal</summary><p>A way to track a specific URL (e.g., /thank-you) as a "Purchase" without coding.</p></details></div><div style="margin-bottom: 15px; padding: 10px; border-bottom: 1px solid #eee;"><strong>3. Hierarchy?</strong><details><summary>Reveal</summary><p>PageView > ViewContent > AddToCart > InitiateCheckout > Purchase.</p></details></div><div style="margin-bottom: 15px; padding: 10px; border-bottom: 1px solid #eee;"><strong>4. Lead vs CompleteRegistration?</strong><details><summary>Reveal</summary><p>Lead is usually for B2B/Service. CompleteRegistration is for Software/Apps.</p></details></div><div style="margin-bottom: 15px; padding: 10px; border-bottom: 1px solid #eee;"><strong>5. Event Setup Tool?</strong><details><summary>Reveal</summary><p>A no-code tool in Events Manager to button-click events.</p></details></div></div>')
    ON CONFLICT (module_id, ordering) DO UPDATE SET title=EXCLUDED.title, content=EXCLUDED.content;

    INSERT INTO lessons (module_id, title, ordering, video_url, content) VALUES
    (v_mod5, 'Conversion Tracking & Attribution', 3, 'https://www.youtube.com/watch?v=62CDBU7Hl2E',
    '<h2>Who Gets the Credit?</h2><p>Attribution is the science of assigning credit to ads.</p><p><strong>The Default: 7-Day Click, 1-Day View.</strong><br>If someone clicks your ad and buys 6 days later, Facebook takes credit. If they see (View) your ad and buy within 24 hours, Facebook takes credit.</p><div style="background-color: #ffffff; border: 2px solid #1877f2; padding: 20px; border-radius: 8px; margin: 20px 0;"><h3 style="color: #1877f2; margin-top: 0; text-align: center;">📝 Knowledge Check</h3><div style="margin-bottom: 15px; padding: 10px; border-bottom: 1px solid #eee;"><strong>1. View-Through Conversion?</strong><details><summary>Reveal</summary><p>A conversion that happened after seeing an ad but NOT clicking it.</p></details></div><div style="margin-bottom: 15px; padding: 10px; border-bottom: 1px solid #eee;"><strong>2. CAPI (Conversions API)?</strong><details><summary>Reveal</summary><p>Server-to-Server tracking. It bypasses the browser (and ad blockers) for better accuracy.</p></details></div><div style="margin-bottom: 15px; padding: 10px; border-bottom: 1px solid #eee;"><strong>3. Deduplication?</strong><details><summary>Reveal</summary><p>Ensuring Pixel and CAPI don''t count the same sale twice.</p></details></div><div style="margin-bottom: 15px; padding: 10px; border-bottom: 1px solid #eee;"><strong>4. Lift Study?</strong><details><summary>Reveal</summary><p>A scientific test where Facebook holds back ads from a group to measure effective lift.</p></details></div><div style="margin-bottom: 15px; padding: 10px; border-bottom: 1px solid #eee;"><strong>5. UTMs?</strong><details><summary>Reveal</summary><p>Universal Tracking Parameters. Use them to double-check Facebook''s homework in Google Analytics.</p></details></div></div>')
    ON CONFLICT (module_id, ordering) DO UPDATE SET title=EXCLUDED.title, content=EXCLUDED.content;

    INSERT INTO lessons (module_id, title, ordering, video_url, content) VALUES
    (v_mod5, 'Offline Conversions & CRM Integration', 4, 'https://www.youtube.com/watch?v=3RkBdJYUL7w',
    '<h2>Closing the Loop</h2><p>What if the sale happens on the phone or in a store?</p><p>You must upload your customer list back to Facebook. Facebook matches the emails/phone numbers to users who saw your ads and reports the "Offline Conversion".</p><div style="background-color: #f0f8ff; border-left: 5px solid #1877f2; padding: 20px; border-radius: 5px; margin: 20px 0;"><h3 style="color: #1877f2; margin-top: 0;">🛠 Practical Exercise</h3><p><strong>CRM Sync:</strong> If you use HubSpot, Salesforce, or Zapier, connect it to Meta "Offline Events". Never do this manually if you can avoid it.</p></div><div style="background-color: #ffffff; border: 2px solid #1877f2; padding: 20px; border-radius: 8px; margin: 20px 0;"><h3 style="color: #1877f2; margin-top: 0; text-align: center;">📝 Knowledge Check</h3><div style="margin-bottom: 15px; padding: 10px; border-bottom: 1px solid #eee;"><strong>1. Match Rate?</strong><details><summary>Reveal</summary><p>The % of your customer list Facebook can identify. 60-80% is great.</p></details></div><div style="margin-bottom: 15px; padding: 10px; border-bottom: 1px solid #eee;"><strong>2. Hashing?</strong><details><summary>Reveal</summary><p>Facebook encrypts data (SHA-256) before upload for privacy.</p></details></div><div style="margin-bottom: 15px; padding: 10px; border-bottom: 1px solid #eee;"><strong>3. Timeliness?</strong><details><summary>Reveal</summary><p>Upload offline data within 48 hours for best attribution.</p></details></div><div style="margin-bottom: 15px; padding: 10px; border-bottom: 1px solid #eee;"><strong>4. Lead Quality usage?</strong><details><summary>Reveal</summary><p>Train the AI to find "Qualified Leads" instead of "Any Lead".</p></details></div><div style="margin-bottom: 15px; padding: 10px; border-bottom: 1px solid #eee;"><strong>5. Privacy Policy?</strong><details><summary>Reveal</summary><p>You must disclose data sharing in your policy.</p></details></div></div>')
    ON CONFLICT (module_id, ordering) DO UPDATE SET title=EXCLUDED.title, content=EXCLUDED.content;

    INSERT INTO lessons (module_id, title, ordering, video_url, content) VALUES
    (v_mod5, 'Troubleshooting Pixel Issues', 5, 'https://www.youtube.com/watch?v=8xM4wC7ZBmE',
    '<h2>Doctor, Doctor</h2><p>Common pixel sicknesses and cures.</p><ul><li><strong>Double Firing:</strong> 1 Purchase counts as 2. (Fix: Check for duplicate code).</li><li><strong>Missing Currency:</strong> Facebook sees "50" but doesn''t know if it''s USD or NGN.</li><li><strong>Domain Not Verified:</strong> Events won''t prioritize correctly (AEM).</li></ul><div style="background-color: #ffffff; border: 2px solid #1877f2; padding: 20px; border-radius: 8px; margin: 20px 0;"><h3 style="color: #1877f2; margin-top: 0; text-align: center;">📝 Knowledge Check</h3><div style="margin-bottom: 15px; padding: 10px; border-bottom: 1px solid #eee;"><strong>1. Diagnostics Tab?</strong><details><summary>Reveal</summary><p>The first place to look in Events Manager for red flags.</p></details></div><div style="margin-bottom: 15px; padding: 10px; border-bottom: 1px solid #eee;"><strong>2. Test Events Tool?</strong><details><summary>Reveal</summary><p>Simulate a purchase yourself and watch it appear in real-time.</p></details></div><div style="margin-bottom: 15px; padding: 10px; border-bottom: 1px solid #eee;"><strong>3. Microdata?</strong><details><summary>Reveal</summary><p>Schema.org data on product pages helping dynamic ads.</p></details></div><div style="margin-bottom: 15px; padding: 10px; border-bottom: 1px solid #eee;"><strong>4. Event Match Quality?</strong><details><summary>Reveal</summary><p>Score (1-10) of how much customer info (email, ip, city) is sent with key events.</p></details></div><div style="margin-bottom: 15px; padding: 10px; border-bottom: 1px solid #eee;"><strong>5. AEM Aggregated Event Measurement?</strong><details><summary>Reveal</summary><p>Ranking your Top 8 events for iOS users.</p></details></div></div>')
    ON CONFLICT (module_id, ordering) DO UPDATE SET title=EXCLUDED.title, content=EXCLUDED.content;


    -- MODULE 6: SCALING & OPTIMIZATION
    
    INSERT INTO lessons (module_id, title, ordering, video_url, content) VALUES
    (v_mod6, 'Reading Performance Data', 1, 'https://www.youtube.com/watch?v=K53x7gaZJ2E',
    '<h2>Data Mining</h2><p>Look for the story in the numbers.</p><div style="background-color: #fff3cd; border-left: 5px solid #ffc107; padding: 20px; border-radius: 5px; margin: 20px 0;"><h3 style="color: #856404; margin-top: 0;">💡 Pro Tip: The "Breakdown Effect"</h3><p>Facebook often puts 80% of spend on one placement (e.g., Feed). Beginners try to force spend elsewhere. Don''t. The algorithm follows the path of least resistance (cheapest conversions).</p></div><div style="background-color: #ffffff; border: 2px solid #1877f2; padding: 20px; border-radius: 8px; margin: 20px 0;"><h3 style="color: #1877f2; margin-top: 0; text-align: center;">📝 Knowledge Check</h3><div style="margin-bottom: 15px; padding: 10px; border-bottom: 1px solid #eee;"><strong>1. Attribution Lag?</strong><details><summary>Reveal</summary><p>Today''s dashboard shows Today''s spend, but maybe 0 sales because they happen tomorrow.</p></details></div><div style="margin-bottom: 15px; padding: 10px; border-bottom: 1px solid #eee;"><strong>2. CPM spikes?</strong><details><summary>Reveal</summary><p>Seasonality (Black Friday) or Creative Fatigue.</p></details></div><div style="margin-bottom: 15px; padding: 10px; border-bottom: 1px solid #eee;"><strong>3. Link Click vs Clicks (All)?</strong><details><summary>Reveal</summary><p>"Clicks (All)" includes likes, expands, and profile clicks. "Link Click" is traffic.</p></details></div><div style="margin-bottom: 15px; padding: 10px; border-bottom: 1px solid #eee;"><strong>4. Video Watches?</strong><details><summary>Reveal</summary><p>ThruPlay (15s) is the standard metric for video success.</p></details></div><div style="margin-bottom: 15px; padding: 10px; border-bottom: 1px solid #eee;"><strong>5. Inspect Tool?</strong><details><summary>Reveal</summary><p>Shows Auction Competition and Audience Saturation graphs.</p></details></div></div>')
    ON CONFLICT (module_id, ordering) DO UPDATE SET title=EXCLUDED.title, content=EXCLUDED.content;

    INSERT INTO lessons (module_id, title, ordering, video_url, content) VALUES
    (v_mod6, 'KPIs That Matter', 2, 'https://www.youtube.com/watch?v=62CDBU7Hl2E',
    '<h2>North Star Metrics</h2><p>Ignore vanity metrics (Likes). Focus on business metrics.</p><table style="width:100%;border-collapse:collapse;margin:20px 0;"><tr><th style="border:1px solid #ddd;padding:10px;">Metric</th><th style="border:1px solid #ddd;padding:10px;">Meaning</th><th style="border:1px solid #ddd;padding:10px;">Goal</th></tr><tr><td style="border:1px solid #ddd;padding:10px;">CPA (Cost Per Acquisition)</td><td style="border:1px solid #ddd;padding:10px;">Cost to get a customer.</td><td style="border:1px solid #ddd;padding:10px;">Must be lower than your Margin.</td></tr><tr><td style="border:1px solid #ddd;padding:10px;">ROAS</td><td style="border:1px solid #ddd;padding:10px;">Revenue multplier.</td><td style="border:1px solid #ddd;padding:10px;">Break-even is usually 1.5 - 2.0x.</td></tr><tr><td style="border:1px solid #ddd;padding:10px;">AOV</td><td style="border:1px solid #ddd;padding:10px;">Average Order Value.</td><td style="border:1px solid #ddd;padding:10px;">Increase this to afford higher ads costs.</td></tr></table><div style="background-color: #ffffff; border: 2px solid #1877f2; padding: 20px; border-radius: 8px; margin: 20px 0;"><h3 style="color: #1877f2; margin-top: 0; text-align: center;">📝 Knowledge Check</h3><div style="margin-bottom: 15px; padding: 10px; border-bottom: 1px solid #eee;"><strong>1. Thumbstop Rate?</strong><details><summary>Reveal</summary><p>% of people who stop scrolling to watch 3s of video. Aim for >30%.</p></details></div><div style="margin-bottom: 15px; padding: 10px; border-bottom: 1px solid #eee;"><strong>2. Hold Rate?</strong><details><summary>Reveal</summary><p>Retention. Are they watching until the end?</p></details></div><div style="margin-bottom: 15px; padding: 10px; border-bottom: 1px solid #eee;"><strong>3. Conversion Rate (CVR)?</strong><details><summary>Reveal</summary><p>Website efficency. If CVR is low (<1%), ads can''t fix it.</p></details></div><div style="margin-bottom: 15px; padding: 10px; border-bottom: 1px solid #eee;"><strong>4. LTV (Lifetime Value)?</strong><details><summary>Reveal</summary><p>The ultimate metric. Allows you to lose money on first sale to win long term.</p></details></div><div style="margin-bottom: 15px; padding: 10px; border-bottom: 1px solid #eee;"><strong>5. MER?</strong><details><summary>Reveal</summary><p>Marketing Efficiency Ratio (Total Revenue / Total Spend). The "Blended ROAS".</p></details></div></div>')
    ON CONFLICT (module_id, ordering) DO UPDATE SET title=EXCLUDED.title, content=EXCLUDED.content;

    INSERT INTO lessons (module_id, title, ordering, video_url, content) VALUES
    (v_mod6, 'Scaling Strategies: Horizontal vs. Vertical', 3, 'https://www.youtube.com/watch?v=8xM4wC7ZBmE',
    '<h2>Turning Up the Volume</h2><p>Scaling is risky. If you double budget, CPA usually rises.</p><ul><li><strong>Vertical Scaling:</strong> Increasing budget on the WINNING Ad Set (20% every 2-3 days).</li><li><strong>Horizontal Scaling:</strong> Finding NEW audiences (Lookalikes 1%, 3%, 5%) and testing the winning creative on them.</li></ul><div style="background-color: #ffffff; border: 2px solid #1877f2; padding: 20px; border-radius: 8px; margin: 20px 0;"><h3 style="color: #1877f2; margin-top: 0; text-align: center;">📝 Knowledge Check</h3><div style="margin-bottom: 15px; padding: 10px; border-bottom: 1px solid #eee;"><strong>1. Learning Phase reset?</strong><details><summary>Reveal</summary><p>Happens if you edit the ad set or increase budget by >20% at once.</p></details></div><div style="margin-bottom: 15px; padding: 10px; border-bottom: 1px solid #eee;"><strong>2. Audience Saturation?</strong><details><summary>Reveal</summary><p>When Frequency hits >3 and CPA rises. You''ve milked the cow dry.</p></details></div><div style="margin-bottom: 15px; padding: 10px; border-bottom: 1px solid #eee;"><strong>3. Broad Targeting?</strong><details><summary>Reveal</summary><p>The ultimate scale. No targeting. Just Age/Gender + Great Creative.</p></details></div><div style="margin-bottom: 15px; padding: 10px; border-bottom: 1px solid #eee;"><strong>4. Surfing?</strong><details><summary>Reveal</summary><p>Increasing budget aggressively on "Good Days" and cutting on "Bad Days".</p></details></div><div style="margin-bottom: 15px; padding: 10px; border-bottom: 1px solid #eee;"><strong>5. Consolidation?</strong><details><summary>Reveal</summary><p>Combining 5 small ad sets into 1 big one to exit the Learning Phase.</p></details></div></div>')
    ON CONFLICT (module_id, ordering) DO UPDATE SET title=EXCLUDED.title, content=EXCLUDED.content;

    INSERT INTO lessons (module_id, title, ordering, video_url, content) VALUES
    (v_mod6, 'Budget Optimization Techniques', 4, 'https://www.youtube.com/watch?v=3RkBdJYUL7w',
    '<h2>Squeezing the Lemon</h2><p>Getting more for less.</p><div style="background-color: #f0f8ff; border-left: 5px solid #1877f2; padding: 20px; border-radius: 5px; margin: 20px 0;"><h3 style="color: #1877f2; margin-top: 0;">🛠 Practical Exercise</h3><p><strong>The "Cost Cap" Sandbox:</strong><br>1. Duplicate your winning campaign.<br>2. Change Bid Strategy to "Cost Cap".<br>3. Set Cap at your Target CPA (e.g., $10).<br>4. Result: Facebook will ONLY spend when it thinks it can get leads for $10.</p></div><div style="background-color: #ffffff; border: 2px solid #1877f2; padding: 20px; border-radius: 8px; margin: 20px 0;"><h3 style="color: #1877f2; margin-top: 0; text-align: center;">📝 Knowledge Check</h3><div style="margin-bottom: 15px; padding: 10px; border-bottom: 1px solid #eee;"><strong>1. CBO (Advantage+ Campaign Budget)?</strong><details><summary>Reveal</summary><p>Let AI shift budget between ad sets automatically.</p></details></div><div style="margin-bottom: 15px; padding: 10px; border-bottom: 1px solid #eee;"><strong>2. Min/Max Spend Limits?</strong><details><summary>Reveal</summary><p>Forcing CBO to spend at least $X on a specific audience.</p></details></div><div style="margin-bottom: 15px; padding: 10px; border-bottom: 1px solid #eee;"><strong>3. Super-Duper Light Speed learning?</strong><details><summary>Reveal</summary><p>Not a real thing. Be patient.</p></details></div><div style="margin-bottom: 15px; padding: 10px; border-bottom: 1px solid #eee;"><strong>4. 50 Conversions Rule?</strong><details><summary>Reveal</summary><p>Need ~50 conversions per week per ad set to stabilize performance.</p></details></div><div style="margin-bottom: 15px; padding: 10px; border-bottom: 1px solid #eee;"><strong>5. Dayparting value?</strong><details><summary>Reveal</summary><p>Mostly a myth for algorithm-based ads. Let the AI run 24/7.</p></details></div></div>')
    ON CONFLICT (module_id, ordering) DO UPDATE SET title=EXCLUDED.title, content=EXCLUDED.content;

    INSERT INTO lessons (module_id, title, ordering, video_url, content) VALUES
    (v_mod6, 'When & How to Kill Underperforming Ads', 5, 'https://www.youtube.com/watch?v=K53x7gaZJ2E',
    '<h2>The Kill Switch</h2><p>Don''t be emotional. Be a sniper.</p><p><strong>The Kill Rules:</strong><br>1. <strong>Spend > 2x Target CPA</strong> with 0 Conversions? KILL.<br>2. <strong>CPC > $3.00</strong> (and normal is $1)? KILL.<br>3. <strong>CTR < 0.5%</strong>? KILL.</p><div style="background-color: #ffffff; border: 2px solid #1877f2; padding: 20px; border-radius: 8px; margin: 20px 0;"><h3 style="color: #1877f2; margin-top: 0; text-align: center;">📝 Knowledge Check</h3><div style="margin-bottom: 15px; padding: 10px; border-bottom: 1px solid #eee;"><strong>1. Soft Kill?</strong><details><summary>Reveal</summary><p>Reducing budget but keeping it alive.</p></details></div><div style="margin-bottom: 15px; padding: 10px; border-bottom: 1px solid #eee;"><strong>2. Pause vs Delete?</strong><details><summary>Reveal</summary><p>Pause. Never delete data. You might need to analyze it later.</p></details></div><div style="margin-bottom: 15px; padding: 10px; border-bottom: 1px solid #eee;"><strong>3. 3-Day Rule?</strong><details><summary>Reveal</summary><p>Don''t kill an ad based on 1 bad day. Look at 3-7 day average.</p></details></div><div style="margin-bottom: 15px; padding: 10px; border-bottom: 1px solid #eee;"><strong>4. Delayed Attribution?</strong><details><summary>Reveal</summary><p>A "loser" on Friday might turn into a "winner" on Monday as reports come in.</p></details></div><div style="margin-bottom: 15px; padding: 10px; border-bottom: 1px solid #eee;"><strong>5. Zombie Ads?</strong><details><summary>Reveal</summary><p>Ads you forgot to turn off that are draining budget.</p></details></div></div>')
    ON CONFLICT (module_id, ordering) DO UPDATE SET title=EXCLUDED.title, content=EXCLUDED.content;


    -- MODULE 7: ADVANCED TACTICS & AUTOMATION
    
    INSERT INTO lessons (module_id, title, ordering, video_url, content) VALUES
    (v_mod7, 'Automated Rules & Scheduling', 1, 'https://www.youtube.com/watch?v=62CDBU7Hl2E',
    '<h2>Set It and Forget It</h2><p>Use rules to protect your wallet while you sleep.</p><p><strong>Essential Rules:</strong><br>1. <strong>Stop Loss:</strong> Turn off ad if Spend > $50 and Results < 1.<br>2. <strong>Watchdog:</strong> Email me if CPM > $40.<br>3. <strong>Winner:</strong> Increase budget 10% if ROAS > 3.0.</p><div style="background-color: #ffffff; border: 2px solid #1877f2; padding: 20px; border-radius: 8px; margin: 20px 0;"><h3 style="color: #1877f2; margin-top: 0; text-align: center;">📝 Knowledge Check</h3><div style="margin-bottom: 15px; padding: 10px; border-bottom: 1px solid #eee;"><strong>1. Action frequency?</strong><details><summary>Reveal</summary><p>Limit rules to run every 30 mins or once daily.</p></details></div><div style="margin-bottom: 15px; padding: 10px; border-bottom: 1px solid #eee;"><strong>2. Rules Window?</strong><details><summary>Reveal</summary><p>Use "Last 3 Days" data, not "Today". "Today" data is too volatile.</p></details></div><div style="margin-bottom: 15px; padding: 10px; border-bottom: 1px solid #eee;"><strong>3. Where to find?</strong><details><summary>Reveal</summary><p>"Rules" button in Ads Manager toolbar.</p></details></div><div style="margin-bottom: 15px; padding: 10px; border-bottom: 1px solid #eee;"><strong>4. Danger of rules?</strong><details><summary>Reveal</summary><p>Accidentally turning off your best ad because of one bad hour.</p></details></div><div style="margin-bottom: 15px; padding: 10px; border-bottom: 1px solid #eee;"><strong>5. Re-enable rule?</strong><details><summary>Reveal</summary><p>Harder to set up. Usually better to turn things back on manually.</p></details></div></div>')
    ON CONFLICT (module_id, ordering) DO UPDATE SET title=EXCLUDED.title, content=EXCLUDED.content;

    INSERT INTO lessons (module_id, title, ordering, video_url, content) VALUES
    (v_mod7, 'CBO vs. ABO: Which to Use When', 2, 'https://www.youtube.com/watch?v=8xM4wC7ZBmE',
    '<h2>The Great Debate</h2><p>Who controls the budget? You or the AI?</p><ul><li><strong>ABO (Ad Set Budget Optimization):</strong> You set budget per audience. Good for <strong>Testing</strong>.</li><li><strong>CBO (Campaign Budget Optimization):</strong> AI sets budget per audience. Good for <strong>Scaling</strong>.</li></ul><div style="background-color: #ffffff; border: 2px solid #1877f2; padding: 20px; border-radius: 8px; margin: 20px 0;"><h3 style="color: #1877f2; margin-top: 0; text-align: center;">📝 Knowledge Check</h3><div style="margin-bottom: 15px; padding: 10px; border-bottom: 1px solid #eee;"><strong>1. Why Test with ABO?</strong><details><summary>Reveal</summary><p>Ensures every variable gets a fair chance (spend) to prove itself.</p></details></div><div style="margin-bottom: 15px; padding: 10px; border-bottom: 1px solid #eee;"><strong>2. Why Scale with CBO?</strong><details><summary>Reveal</summary><p>AI reacts faster than you. It moves money to the hottest audience instantly.</p></details></div><div style="margin-bottom: 15px; padding: 10px; border-bottom: 1px solid #eee;"><strong>3. One Ad Set CBO?</strong><details><summary>Reveal</summary><p>Same as ABO.</p></details></div><div style="margin-bottom: 15px; padding: 10px; border-bottom: 1px solid #eee;"><strong>4. 70/30 split?</strong><details><summary>Reveal</summary><p>Common issue where CBO spends 70% on largest audience. Normal behavior.</p></details></div><div style="margin-bottom: 15px; padding: 10px; border-bottom: 1px solid #eee;"><strong>5. Proven strategy?</strong><details><summary>Reveal</summary><p>Find winners in ABO. Move winners to CBO.</p></details></div></div>')
    ON CONFLICT (module_id, ordering) DO UPDATE SET title=EXCLUDED.title, content=EXCLUDED.content;

    INSERT INTO lessons (module_id, title, ordering, video_url, content) VALUES
    (v_mod7, 'Retargeting with Catalogs & Dynamic Ads', 3, 'https://www.youtube.com/watch?v=3RkBdJYUL7w',
    '<h2>DPA (Dynamic Product Ads)</h2><p>The "Magic" ads that follow you around the internet.</p><p>Instead of manually creating an ad for every product, you upload a csv "Catalog". Facebook dynamically generates the ad based on what the user viewed on your site.</p><div style="background-color: #f0f8ff; border-left: 5px solid #1877f2; padding: 20px; border-radius: 5px; margin: 20px 0;"><h3 style="color: #1877f2; margin-top: 0;">🛠 Practical Exercise</h3><p><strong>Set up DPA:</strong> 1. Commerce Manager > Create Catalog. 2. Objective: Sales > Catalog Sales. 3. Audience: "Viewed or Added to Cart but not Purchased (14 Days)".</p></div><div style="background-color: #ffffff; border: 2px solid #1877f2; padding: 20px; border-radius: 8px; margin: 20px 0;"><h3 style="color: #1877f2; margin-top: 0; text-align: center;">📝 Knowledge Check</h3><div style="margin-bottom: 15px; padding: 10px; border-bottom: 1px solid #eee;"><strong>1. DABA?</strong><details><summary>Reveal</summary><p>Dynamic Ads for Broad Audiences. Showing catalog items to cold traffic.</p></details></div><div style="margin-bottom: 15px; padding: 10px; border-bottom: 1px solid #eee;"><strong>2. Overlays?</strong><details><summary>Reveal</summary><p>Automatically adding price or "Free Shipping" badge to image.</p></details></div><div style="margin-bottom: 15px; padding: 10px; border-bottom: 1px solid #eee;"><strong>3. Catalog Match Rate?</strong><details><summary>Reveal</summary><p>% of products on website that match the catalog. Fix mismatch errors!</p></details></div><div style="margin-bottom: 15px; padding: 10px; border-bottom: 1px solid #eee;"><strong>4. Collections DPA?</strong><details><summary>Reveal</summary><p>A big hero video with dynamic products underneath.</p></details></div><div style="margin-bottom: 15px; padding: 10px; border-bottom: 1px solid #eee;"><strong>5. Sets?</strong><details><summary>Reveal</summary><p>Grouping products (e.g., "Shirts Only") to control what is shown.</p></details></div></div>')
    ON CONFLICT (module_id, ordering) DO UPDATE SET title=EXCLUDED.title, content=EXCLUDED.content;

    INSERT INTO lessons (module_id, title, ordering, video_url, content) VALUES
    (v_mod7, 'Using UTM Parameters for Deep Analytics', 4, 'https://www.youtube.com/watch?v=K53x7gaZJ2E',
    '<h2>Trust But Verify</h2><p>UTMs are tags added to the end of your URL (e.g., ?utm_source=facebook).</p><p>Why? Because Google Analytics tells a different story than Facebook Ads Manager. You need the truth.</p><div style="background-color: #ffffff; border: 2px solid #1877f2; padding: 20px; border-radius: 8px; margin: 20px 0;"><h3 style="color: #1877f2; margin-top: 0; text-align: center;">📝 Knowledge Check</h3><div style="margin-bottom: 15px; padding: 10px; border-bottom: 1px solid #eee;"><strong>1. Dynamic URL params?</strong><details><summary>Reveal</summary><p>{{campaign.name}} automatically inserts the campaign name.</p></details></div><div style="margin-bottom: 15px; padding: 10px; border-bottom: 1px solid #eee;"><strong>2. Source vs Medium?</strong><details><summary>Reveal</summary><p>Source = Facebook. Medium = CPC/Paid.</p></details></div><div style="margin-bottom: 15px; padding: 10px; border-bottom: 1px solid #eee;"><strong>3. Dark Traffic?</strong><details><summary>Reveal</summary><p>Traffic with no referrer info (Direct). UTMs fix this.</p></details></div><div style="margin-bottom: 15px; padding: 10px; border-bottom: 1px solid #eee;"><strong>4. Campaign ID param?</strong><details><summary>Reveal</summary><p>h_ad_id={{ad.id}}. Essential for third-party trackers like Hyros/TripleWhale.</p></details></div><div style="margin-bottom: 15px; padding: 10px; border-bottom: 1px solid #eee;"><strong>5. Shorteners?</strong><details><summary>Reveal</summary><p>Avoid bit.ly in ads. Facebook dislikes redirects.</p></details></div></div>')
    ON CONFLICT (module_id, ordering) DO UPDATE SET title=EXCLUDED.title, content=EXCLUDED.content;

    INSERT INTO lessons (module_id, title, ordering, video_url, content) VALUES
    (v_mod7, 'Integrating Facebook Ads with Email Funnels', 5, 'https://www.youtube.com/watch?v=62CDBU7Hl2E',
    '<h2>The Omni-Channel machine</h2><p>Ads start the fire. Email keeps it burning.</p><p><strong>Strategy:</strong><br>1. Run Lead Ad on Facebook.<br>2. Send Lead to Email Provider (Zapier).<br>3. Send "Welcome Series" (5 emails).<br>4. If they don''t buy, upload email list to Facebook as Custom Audience.<br>5. Show "Last Chance" ad.</p><div style="background-color: #ffffff; border: 2px solid #1877f2; padding: 20px; border-radius: 8px; margin: 20px 0;"><h3 style="color: #1877f2; margin-top: 0; text-align: center;">📝 Knowledge Check</h3><div style="margin-bottom: 15px; padding: 10px; border-bottom: 1px solid #eee;"><strong>1. Owned Audience?</strong><details><summary>Reveal</summary><p>Email/SMS. You own it. No algorithms.</p></details></div><div style="margin-bottom: 15px; padding: 10px; border-bottom: 1px solid #eee;"><strong>2. Renting Audience?</strong><details><summary>Reveal</summary><p>Ads. You pay for access.</p></details></div><div style="margin-bottom: 15px; padding: 10px; border-bottom: 1px solid #eee;"><strong>3. Sync frequency?</strong><details><summary>Reveal</summary><p>Dynamic sync (Real-time). Don''t do manual CSV uploads.</p></details></div><div style="margin-bottom: 15px; padding: 10px; border-bottom: 1px solid #eee;"><strong>4. Exclusion strategy?</strong><details><summary>Reveal</summary><p>Exclude existing subscribers from "Newsletter Sign Up" ads.</p></details></div><div style="margin-bottom: 15px; padding: 10px; border-bottom: 1px solid #eee;"><strong>5. Win-back campaign?</strong><details><summary>Reveal</summary><p>Targeting lapsed customers (haven''t bought in 180 days).</p></details></div></div>')
    ON CONFLICT (module_id, ordering) DO UPDATE SET title=EXCLUDED.title, content=EXCLUDED.content;

END $$;
