-- UPDATE FINAL LESSONS 23-26: WHEN NOT TO USE AI, APPLICATIONS & CAREER
-- Run this in Supabase SQL Editor

-- LESSON 23: When NOT to Use AI
UPDATE lessons SET
    content = '<h2>The Danger Zone: When AI Should Stay Out</h2><p>AI is powerful, but not always appropriate. Knowing when NOT to use it is advanced Vibe Coding wisdom.</p><h3>Never Give AI:</h3><ul><li><strong>Secrets</strong>: API keys, passwords, private keys. AI remembers context.</li><li><strong>PII</strong>: Personal Identifiable Information - avoid training it on user data.</li><li><strong>Core IP</strong>: Trade secrets, proprietary algorithms that define your business.</li><li><strong>Production Credentials</strong>: Database passwords, admin tokens.</li></ul><h3>When Manual is Better:</h3><ul><li><strong>Already Know Exactly What to Write</strong>: Faster to type it yourself</li><li><strong>Very Small Changes</strong>: Changing one variable name</li><li><strong>Security-Critical Code</strong>: Auth logic, encryption - verify every line</li><li><strong>Highly Context-Dependent</strong>: Deep legacy system knowledge</li></ul><h3>The 80/20 Rule of AI</h3><p>AI handles 80% of tasks well. The remaining 20% requires careful human judgment. Know which is which.</p><h3>Red Flags</h3><ul><li>AI keeps ''almost'' getting it right</li><li>You''re spending more time fixing than building</li><li>The task requires deep institutional knowledge</li><li>Security/compliance is critical</li></ul><h3>The Human Touch</h3><p>Some things AI cannot do: understand YOUR users, YOUR business, YOUR taste. Domain expertise is irreplaceable.</p>',
    summary = 'Know when NOT to use AI: secrets, PII, security-critical code, and when you already know exactly what to write.',
    case_studies = '[{"title": "The Leaked API Key", "scenario": "A developer pasted their production Stripe key into an AI prompt. The key appeared in training data.", "analysis": "AI providers may use prompts for training. Secrets in prompts can leak.", "outcome": "Key revoked, new key generated, lesson learned: NEVER paste secrets into AI context. Use placeholders."}]'::jsonb,
    key_takeaways = '["Never paste secrets, passwords, or API keys into AI prompts.", "Manual is faster when you already know exactly what to write.", "Domain expertise and institutional knowledge are irreplaceable."]'::jsonb,
    quizzes = '[{"question": "What should you NEVER give AI?", "options": ["Questions", "Secrets and API keys", "Public documentation", "Open source code"], "correctAnswer": 1, "explanation": "Secrets in AI prompts can potentially leak or be used in training."}, {"question": "When is manual coding faster?", "options": ["Never", "When you already know exactly what to write", "Always", "Only for experts"], "correctAnswer": 1, "explanation": "Small, well-known changes are faster to type than prompt."}, {"question": "What is the 80/20 rule of AI?", "options": ["Use AI 80% of the time", "AI handles 80% well, 20% needs human judgment", "AI is 80% accurate", "Use AI for 20% of work"], "correctAnswer": 1, "explanation": "Most tasks work well with AI; some require human expertise."}, {"question": "When should you especially verify AI code?", "options": ["Never", "Security-critical code like auth and encryption", "Only in production", "Only for new projects"], "correctAnswer": 1, "explanation": "Security code needs human verification for every line."}, {"question": "What can AI NOT replace?", "options": ["Typing", "Domain expertise and institutional knowledge", "Formatting", "Syntax"], "correctAnswer": 1, "explanation": "AI cannot understand YOUR specific users, business, and context."}]'::jsonb,
    videos = '[{"title": "Security Best Practices with AI", "url": "https://www.youtube.com/embed/Sal7cz3T40M", "why_this_video": "Essential security practices when using AI coding tools."}]'::jsonb,
    playground = '{"objective": "Identify scenarios where AI should and should not be used", "environment": "cursor", "starter_prompt": "Classify these 10 tasks as AI-appropriate or human-only", "guided_steps": ["List 5 tasks perfect for AI", "List 5 tasks that need human judgment", "For each human-only task, explain why", "Practice using placeholders for sensitive values", "Create a team guide: When to use AI"], "advanced_challenge": "Create an AI usage policy for a security-conscious organization", "failure_mode_experiment": "Observe what happens when you prompt AI about internal systems it has no context for", "real_world_simulation": "Audit your recent AI usage for inappropriate information sharing"}'::jsonb,
    duration = 15
WHERE title = 'When NOT to Use AI';

-- LESSON 24: Internal Tools
UPDATE lessons SET
    content = '<h2>The Hidden Economy: Building Internal Tools</h2><p>The most underrated Vibe Coding opportunity: internal tools. Every company needs them. Few build them well.</p><h3>The Internal Tool Goldmine</h3><ul><li><strong>Admin Dashboards</strong>: User management, data viewing</li><li><strong>Data Entry Forms</strong>: CRMs, inventory, operations</li><li><strong>Reporting</strong>: Charts, exports, analytics</li><li><strong>Automation Triggers</strong>: Batch operations, scheduled tasks</li><li><strong>Integration Glue</strong>: Connect systems that don''t talk</li></ul><h3>Why This is Profitable</h3><p>Businesses spend 10-50K on internal tools. With Vibe Coding, you can build them in days. The margin is enormous.</p><h3>The Internal Tool Stack</h3><ul><li><strong>Retool</strong>: Drag-and-drop, connects to databases</li><li><strong>Airplane</strong>: Developer-first internal tools</li><li><strong>Supabase Studio</strong>: Instant admin for Postgres</li><li><strong>Custom React</strong>: For unique requirements</li></ul><h3>Becoming the Toolsmith</h3><p>In any organization, the person who can rapidly build internal tools is invaluable. You become the bottleneck-breaker.</p><h3>Common Internal Tool Requests</h3><ol><li>''I need to see X data in a spreadsheet-like view''</li><li>''I need to bulk update Y records''</li><li>''I need a form to Z with validation''</li><li>''I need this report emailed every Monday''</li></ol>',
    summary = 'Internal tools are a goldmine: high value, fast delivery with AI. Become the toolsmith who removes organizational bottlenecks.',
    case_studies = '[{"title": "The $30K Weekend", "scenario": "A consultant was asked to build an inventory management admin. Quote from agencies: $30K, 8 weeks.", "analysis": "Using Retool + Vibe Coding, built in 3 days. Clean interface, full CRUD, role-based access.", "outcome": "Charged $8K, delivered in 1 week. Client saved $22K. Consultant worked 3 days for $8K."}]'::jsonb,
    key_takeaways = '["Internal tools have enormous margins - high value, fast delivery.", "Retool, Airplane, and custom React cover 90% of internal tool needs.", "Being the toolsmith makes you invaluable in any organization."]'::jsonb,
    quizzes = '[{"question": "Why are internal tools profitable?", "options": ["They are complex", "High business value, fast AI-assisted delivery", "No one needs them", "They are free"], "correctAnswer": 1, "explanation": "Companies pay well for tools that save time; AI makes delivery fast."}, {"question": "What is Retool best for?", "options": ["Mobile games", "Admin dashboards connecting to databases", "Video editing", "Social media"], "correctAnswer": 1, "explanation": "Retool specializes in database-connected admin interfaces."}, {"question": "What does a toolsmith do?", "options": ["Makes hammers", "Rapidly builds internal tools that remove bottlenecks", "Writes documentation", "Manages servers"], "correctAnswer": 1, "explanation": "The toolsmith solves organizational problems with quick internal tools."}, {"question": "What are common internal tool requests?", "options": ["Games", "Data views, bulk updates, forms, scheduled reports", "AI training", "Hardware"], "correctAnswer": 1, "explanation": "Most requests involve viewing/editing data, forms, and reports."}, {"question": "What margin is possible on internal tools?", "options": ["None", "3-10x markup over actual time invested", "Negative", "Very low"], "correctAnswer": 1, "explanation": "AI reduces build time dramatically while business value remains high."}]'::jsonb,
    videos = '[{"title": "Building Internal Tools Fast", "url": "https://www.youtube.com/embed/6qg5iI_n8m0", "why_this_video": "How to rapidly build valuable internal tools with modern approaches."}]'::jsonb,
    playground = '{"objective": "Build an internal tool for a common business need", "environment": "cursor", "starter_prompt": "Build an admin dashboard to view and edit customer records with search and filtering", "guided_steps": ["Identify a common internal tool need", "Choose approach: Retool, custom React, or Airplane", "Build the data table view", "Add search and filtering", "Implement edit functionality", "Add role-based access control"], "advanced_challenge": "Build 3 different internal tools in one weekend", "failure_mode_experiment": "Try to scope an internal tool request without understanding the business process", "real_world_simulation": "Find an actual internal tool pain point in your organization and solve it"}'::jsonb,
    duration = 20
WHERE title = 'Internal Tools';

-- LESSON 25: Client Work
UPDATE lessons SET
    content = '<h2>Value-Based Pricing: Client Work in the AI Era</h2><p>Billing by the hour is dead. Vibe Coding makes it absurd. Bill by outcome.</p><h3>The Pricing Shift</h3><ul><li><strong>Old Model</strong>: $100/hour x 80 hours = $8,000</li><li><strong>New Model</strong>: This feature saves you $50K/year = $10,000 one-time</li></ul><p>Your speed is your advantage. Don''t compete on hours; compete on outcomes.</p><h3>Value-Based Pricing Formula</h3><p>What is X worth to the client if done well? Charge 10-20% of that value. They pay $10K, they get $50K+ value. Everyone wins.</p><h3>Productizing Your Services</h3><ul><li><strong>MVP Sprint</strong>: $5-10K, 2 weeks, working product</li><li><strong>Feature Build</strong>: $2-5K, specific feature with validation</li><li><strong>AI Integration</strong>: $3-8K, add AI to existing product</li><li><strong>Internal Tool</strong>: $3-10K, admin dashboards, automation</li></ul><h3>Client Communication</h3><p>Don''t talk about AI. Talk about results. Clients care about outcomes, not how you achieve them.</p><h3>Delivery Excellence</h3><ol><li>Clear scope (written, signed)</li><li>Regular updates (weekly)</li><li>Working demos (not just descriptions)</li><li>Documentation (so they can maintain)</li></ol>',
    summary = 'Bill by outcome, not hours. AI makes hourly pricing absurd. Productize your services: MVP Sprints, Feature Builds, Internal Tools.',
    case_studies = '[{"title": "The $15K Week", "scenario": "A freelancer took on an MVP project. Old approach: 2 months. New approach: 1 week with Vibe Coding.", "analysis": "Charged $15K flat rate for ''Working MVP with auth, core feature, and payments.'' Delivered Friday.", "outcome": "Client got a $50K+ value product for $15K. Freelancer worked ~40 hours for $15K = $375/hour effective rate."}]'::jsonb,
    key_takeaways = '["Bill by outcome, not hours - AI makes hourly absurd.", "Productize: MVP Sprint, Feature Build, Internal Tool packages.", "Do not talk about AI - talk about results and outcomes."]'::jsonb,
    quizzes = '[{"question": "Why is hourly billing obsolete?", "options": ["It pays too much", "AI makes delivery so fast that hourly underpays you", "Clients prefer it", "It is illegal"], "correctAnswer": 1, "explanation": "If you deliver in 5 hours what used to take 50, hourly pricing hurts you."}, {"question": "How should you price AI-assisted work?", "options": ["By the hour", "By outcome value to the client", "Always free", "By number of lines"], "correctAnswer": 1, "explanation": "Charge based on the value delivered, not time spent."}, {"question": "What is productizing?", "options": ["Making physical products", "Packaging services into defined offerings with fixed prices", "Adding features", "Marketing"], "correctAnswer": 1, "explanation": "Productizing means fixed-scope, fixed-price service packages."}, {"question": "Should you tell clients about AI?", "options": ["Yes, always", "Focus on outcomes, not methods", "Never work for clients", "Only if they ask"], "correctAnswer": 1, "explanation": "Clients care about results, not how you achieve them."}, {"question": "What makes delivery excellent?", "options": ["Speed only", "Clear scope, updates, demos, and documentation", "Low price", "Long contracts"], "correctAnswer": 1, "explanation": "Professional delivery includes scope clarity, communication, and handoff."}]'::jsonb,
    videos = '[{"title": "Value-Based Pricing for Developers", "url": "https://www.youtube.com/embed/pU72h2Zbc5c", "why_this_video": "How to price development work based on outcomes, not hours."}]'::jsonb,
    playground = '{"objective": "Practice scoping and pricing a client project", "environment": "cursor", "starter_prompt": "A client needs a booking system for their salon. Write a scope document and price proposal.", "guided_steps": ["Define the client outcome: What do they get?", "List features included and excluded", "Estimate value to client (time saved, revenue enabled)", "Set price at 10-20% of value", "Write a one-page proposal", "Add delivery timeline and milestones"], "advanced_challenge": "Create 3 productized service offerings with fixed scope and price", "failure_mode_experiment": "Compare hourly rate vs value-based pricing for the same project", "real_world_simulation": "Write a proposal for an actual potential client"}'::jsonb,
    duration = 20
WHERE title = 'Client Work';

-- LESSON 26: The Future of Software
UPDATE lessons SET
    content = '<h2>Software as a Commodity: The Future of Building</h2><p>Code is becoming abundant. Everyone will be able to build. What becomes scarce? Taste. Vision. Judgment.</p><h3>The Abundance of Code</h3><p>When anyone can build an app with natural language, the ability to code is not the differentiator. The ability to know WHAT to build is.</p><h3>What Becomes Valuable</h3><ul><li><strong>Taste</strong>: Knowing what makes a great product</li><li><strong>Vision</strong>: Seeing the future of a market</li><li><strong>Judgment</strong>: Deciding what to build and what not to</li><li><strong>Domain Expertise</strong>: Understanding specific industries deeply</li><li><strong>Orchestration</strong>: Managing systems and agents at scale</li></ul><h3>The Coming Landscape</h3><ol><li><strong>Solo Builders Rise</strong>: One person = entire product teams</li><li><strong>Ideas Become Testing</strong>: Build prototypes in hours, not months</li><li><strong>Custom Software Everywhere</strong>: Every niche gets custom tools</li><li><strong>AI as Teammate</strong>: Agents become persistent collaborators</li></ol><h3>Your Position</h3><p>By completing this course, you''re ahead of 99% of people. Most haven''t even started. You''re building the skills for the future economy.</p><h3>The Path Forward</h3><ol><li>Keep building - daily practice</li><li>Stay current - tools evolve fast</li><li>Share knowledge - teach others</li><li>Build taste - study great products</li><li>Develop domain expertise - pick an industry</li></ol><h3>Congratulations</h3><p>You''ve completed Vibe Coding 3.0. You''re now a Vibe Coder. Go build the future.</p>',
    summary = 'Code is becoming abundant; taste, vision, and judgment become scarce and valuable. Solo builders can now create what used to require teams.',
    case_studies = '[{"title": "The One-Person Unicorn", "scenario": "Historical: Instagram was acquired for $1B with 13 employees. Future: solo founders achieving similar outcomes.", "analysis": "AI enables one person to do the work of entire teams. The trend is accelerating.", "outcome": "We will see billion-dollar outcomes from single individuals or tiny teams. The leverage is unprecedented."}]'::jsonb,
    key_takeaways = '["Code becomes commodity; taste, vision, judgment become scarce.", "Solo builders can now create what used to require teams.", "You are ahead of 99% of people by completing this course."]'::jsonb,
    quizzes = '[{"question": "What becomes valuable when code is abundant?", "options": ["More code", "Taste, vision, and judgment", "Longer hours", "More languages"], "correctAnswer": 1, "explanation": "When anyone can code, knowing WHAT to build becomes the differentiator."}, {"question": "What is the future of solo builders?", "options": ["Obsolete", "One person can create what used to require teams", "No change", "Less important"], "correctAnswer": 1, "explanation": "AI leverage means solo founders can achieve unprecedented scale."}, {"question": "Why is domain expertise valuable?", "options": ["It is not", "AI cannot understand specific industries deeply", "It is free", "Everyone has it"], "correctAnswer": 1, "explanation": "Deep industry knowledge is hard to replicate and guides what to build."}, {"question": "What is orchestration in AI terms?", "options": ["Music", "Managing AI agents and systems at scale", "Typing fast", "Database design"], "correctAnswer": 1, "explanation": "Orchestration means directing multiple AI agents to work together."}, {"question": "What should you do after this course?", "options": ["Stop learning", "Keep building, stay current, share knowledge, develop taste", "Wait for better AI", "Nothing"], "correctAnswer": 1, "explanation": "Continuous practice and learning is the path forward."}]'::jsonb,
    videos = '[{"title": "The Future of Software Development", "url": "https://www.youtube.com/embed/5EFd0n_n7bU", "why_this_video": "Vision of where software development is heading in the age of AI."}]'::jsonb,
    playground = '{"objective": "Plan your post-course path as a Vibe Coder", "environment": "cursor", "starter_prompt": "Define your Vibe Coding specialty and 90-day plan", "guided_steps": ["Identify your domain expertise or interest", "List 3 products you could build in that domain", "Pick one to prototype this week", "Create a learning plan to stay current", "Find a community or person to share knowledge with"], "advanced_challenge": "Launch your first AI-built product within 30 days", "failure_mode_experiment": "Try to build without any plan and observe the difference", "real_world_simulation": "Start your first real project using everything from this course"}'::jsonb,
    duration = 20
WHERE title = 'The Future of Software';

-- Final Verification (simple version)
SELECT 
    title, 
    LENGTH(content) as content_length,
    CASE WHEN playground IS NOT NULL THEN 'Yes' ELSE 'No' END as has_playground,
    CASE WHEN videos IS NOT NULL THEN 'Yes' ELSE 'No' END as has_videos
FROM lessons
WHERE title IN (
    'When NOT to Use AI',
    'Internal Tools',
    'Client Work',
    'The Future of Software'
)
ORDER BY title;
