-- UPDATE LESSON 1 WITH FULL SPECIFICATION-COMPLIANT CONTENT
-- Run this in Supabase SQL Editor

UPDATE lessons
SET 
    content = '<h2>The Shift from Syntax to Intent</h2><p>In the traditional world of software development, mastery meant memorizing syntax, understanding compiler quirks, and spending years building muscle memory for typing code. A senior developer was someone who could write a complex algorithm from scratch, debug memory leaks, and navigate the intricate dance of semicolons and brackets that defined their craft.</p><p><strong>That world is ending.</strong></p><p>Vibe Coding represents a fundamental paradigm shift in how software is created. It''s not about typing code faster or memorizing more syntax—it''s about <em>communicating intent</em> to AI systems that translate your vision into executable software.</p><h3>The Core Principle: Intent Over Implementation</h3><p>At its heart, Vibe Coding operates on a simple but revolutionary principle: <strong>if you can describe what you want clearly and precisely, you can build it</strong>. The ''how'' becomes the AI''s responsibility. Your job is the ''what'' and the ''why''.</p><p>Consider this mental model: Traditional coding is like being a bricklayer—you place each brick (line of code) yourself, understanding exactly how the mortar (syntax) holds everything together. Vibe Coding is like being an architect—you design the building, specify the requirements, and direct the construction, but you don''t personally lay every brick.</p><h3>Why Syntax-First Learning Has Collapsed</h3><p>For decades, learning to code meant starting with ''Hello World'' and gradually working up through variables, loops, functions, classes, and frameworks. This bottom-up approach made sense when writing code was the primary bottleneck. But consider these statistics:</p><ul><li>80% of code in any project is boilerplate—repetitive patterns that AI can generate instantly</li><li>The average developer spends only 35% of their time actually writing new code</li><li>AI code completion tools now suggest accurate code 40-60% of the time</li></ul><h3>The New Developer Skillset</h3><p>Vibe Coding requires a fundamentally different skillset:</p><ol><li><strong>Problem Decomposition</strong>: Breaking large problems into smaller, AI-digestible chunks</li><li><strong>Intent Articulation</strong>: Expressing what you want with precision and clarity</li><li><strong>Quality Judgment</strong>: Evaluating AI output and knowing when it''s wrong</li><li><strong>System Thinking</strong>: Understanding how components interact</li><li><strong>Rapid Iteration</strong>: Moving fast through multiple AI-generated solutions</li></ol><p>The goal is not to replace your brain with AI—it''s to extend your capabilities by orders of magnitude.</p>',
    
    summary = 'Vibe Coding represents a paradigm shift from syntax-focused development to intent-driven creation. Instead of memorizing programming languages, developers now orchestrate AI tools to translate clear descriptions into working software.',
    
    case_studies = '[{"title": "The Solo Developer Who Built a SaaS in 48 Hours", "scenario": "Marcus, a non-technical founder, wanted to build a customer feedback tool using only AI-assisted coding.", "analysis": "Using Cursor and Claude, Marcus described each feature conversationally. He started with simple prompts and iterated based on AI output.", "outcome": "48 hours later, Marcus had a working MVP with authentication, real-time voting, and email notifications. He launched and got 500 users in week one."}]'::jsonb,
    
    key_takeaways = '["Intent Over Syntax: If you can describe it precisely, you can build it.", "Conductor Mindset: You are orchestrating the AI, not playing every instrument.", "Value Migration: The bottleneck has shifted from writing code to defining problems correctly."]'::jsonb,
    
    quizzes = '[{"question": "What is the core principle of Vibe Coding?", "options": ["Writing code faster", "Communicating intent to AI systems", "Memorizing more languages", "Automating all decisions"], "correctAnswer": 1, "explanation": "Vibe Coding is about communicating your intent clearly to AI systems."}, {"question": "What percentage of code is typically boilerplate?", "options": ["20%", "50%", "80%", "95%"], "correctAnswer": 2, "explanation": "Approximately 80% of code is boilerplate that AI can generate instantly."}, {"question": "Which mental model best describes Vibe Coding?", "options": ["Bricklayer", "Conductor", "Athlete", "Librarian"], "correctAnswer": 1, "explanation": "A conductor orchestrates various AI tools to create cohesive software."}, {"question": "What is a common failure mode for new Vibe Coders?", "options": ["Writing too much manual code", "Using too specific prompts", "Giving vague prompts", "Verifying output too thoroughly"], "correctAnswer": 2, "explanation": "Vague prompts lead to unpredictable results."}, {"question": "How does Vibe Coding change software economics?", "options": ["Increases cost", "Makes production near-zero cost", "Eliminates developers", "Makes frontend more expensive"], "correctAnswer": 1, "explanation": "Value migrates from code production to problem definition."}]'::jsonb,
    
    videos = '[{"title": "The Future of Programming with AI", "url": "https://www.youtube.com/embed/yO7-wV7pPZQ", "why_this_video": "Essential context for understanding the shift to AI-assisted development."}]'::jsonb,
    
    playground = '{"objective": "Experience your first Vibe Coding session by building a todo app using only natural language", "environment": "cursor", "starter_prompt": "Create a simple React todo app with add, complete, and delete functionality.", "guided_steps": ["Open Cursor", "Create a new React project", "Paste the starter prompt", "Review and refine"], "advanced_challenge": "Extend to persist data to localStorage", "failure_mode_experiment": "Give a deliberately vague prompt and observe", "real_world_simulation": "Pretend you are a non-technical founder describing a feedback widget"}'::jsonb,
    
    duration = 15

WHERE title = 'What Is Vibe Coding (Deep)';

-- Verify
SELECT title, 
       LENGTH(content) as content_length,
       jsonb_array_length(quizzes) as quiz_count,
       jsonb_array_length(key_takeaways) as takeaway_count,
       playground IS NOT NULL as has_playground
FROM lessons 
WHERE title = 'What Is Vibe Coding (Deep)';
