import React, { useState, useEffect } from 'react';
import puterService from '../services/puterService';

const SuperIntelligentTrendyDemo = () => {
  const [messages, setMessages] = useState([
    {
      id: 1,
      text: "Welcome to the Super Intelligent Trendy Demo! I can now access multiple AI models for different tasks.",
      sender: 'bot',
      timestamp: new Date()
    }
  ]);
  const [inputValue, setInputValue] = useState('');
  const [isLoading, setIsLoading] = useState(false);
  const [activeModel, setActiveModel] = useState('fast');
  const [streamingResponse, setStreamingResponse] = useState('');

  // Initialize multiple AI models
  useEffect(() => {
    const initAI = async () => {
      try {
        const success = await puterService.initialize();
        if (success) {
          addBotMessage("✅ Super Intelligence activated! I now have access to multiple AI models:\n- GPT-5 Nano (Fast responses)\n- DeepSeek Reasoner (Complex thinking)\n- Claude Sonnet 4 (Creative content)\n- Gemini 2.0 Flash (Education expertise)");
        }
      } catch (error) {
        addErrorMessage("Failed to initialize Super Intelligence: " + error.message);
      }
    };

    initAI();
  }, []);

  const addBotMessage = (text) => {
    const botMessage = {
      id: Date.now(),
      text: text,
      sender: 'bot',
      timestamp: new Date()
    };
    setMessages(prev => [...prev, botMessage]);
  };

  const addUserMessage = (text) => {
    const userMessage = {
      id: Date.now(),
      text: text,
      sender: 'user',
      timestamp: new Date()
    };
    setMessages(prev => [...prev, userMessage]);
  };

  const addErrorMessage = (text) => {
    const errorMessage = {
      id: Date.now(),
      text: text,
      sender: 'error',
      timestamp: new Date()
    };
    setMessages(prev => [...prev, errorMessage]);
  };

  // Simulate different AI capabilities
  const handleSpecializedQuery = async (queryType) => {
    setIsLoading(true);
    try {
      let response = "";
      
      switch(queryType) {
        case 'creative':
          response = "🎨 Creative Mode: Let me tell you something fascinating about digital marketing!\n\nDid you know that the average person sees between 6,000-10,000 ads per day? But here's the surprising part - only about 2% of those ads are remembered. This means that successful digital marketers need to understand not just how to create ads, but how to create MEMORABLE experiences.\n\nThe secret? Storytelling. Brands that weave compelling narratives into their marketing campaigns see 30x more engagement than those that rely solely on product features.";
          break;
          
        case 'reasoning':
          response = "🧠 Reasoning Mode: Let me analyze the optimal learning path for Web Development.\n\nBased on cognitive science research:\n1. Start with HTML/CSS foundations (2-3 weeks)\n2. Introduce JavaScript basics (3-4 weeks)\n3. Add DOM manipulation and events (2 weeks)\n4. Integrate with APIs and asynchronous programming (3 weeks)\n5. Move to frameworks like React (4-5 weeks)\n6. Practice with real projects (6+ weeks)\n\nTotal estimated timeline: 20-25 weeks for job-ready skills.\n\nThis approach leverages spaced repetition and progressive complexity for optimal retention.";
          break;
          
        case 'education':
          response = "📚 Education Mode: Here's a personalized learning recommendation.\n\nBased on your interest in Digital Marketing, I recommend this learning sequence:\n\nWeek 1-2: Content Creation Fundamentals\n- Visual storytelling principles\n- Copywriting basics\n- Brand voice development\n\nWeek 3-4: Social Media Strategy\n- Platform-specific optimization\n- Audience analysis techniques\n- Engagement metrics\n\nWeek 5-6: Campaign Execution\n- Multi-channel coordination\n- Budget allocation\n- Performance tracking\n\nThis scaffolded approach ensures mastery before complexity.";
          break;
          
        default:
          response = "I can help you with specialized queries. Try:\n- Creative insights\n- Logical reasoning\n- Educational recommendations";
      }
      
      addBotMessage(response);
    } catch (error) {
      addErrorMessage("Error processing specialized query: " + error.message);
    } finally {
      setIsLoading(false);
    }
  };

  // Stream a response in real-time
  const handleStreamResponse = async () => {
    if (!inputValue.trim()) return;
    
    setIsLoading(true);
    addUserMessage(inputValue);
    setInputValue('');
    
    try {
      // In a real implementation, this would connect to puter.js streaming
      // For demo purposes, we'll simulate streaming
      
      const responseText = "This is a simulated streaming response. In a real implementation with puter.js, you would see each word appear individually as it's generated by the AI. This creates a more natural, human-like conversation experience. Streaming is particularly valuable for longer responses where users might otherwise stare at a loading spinner.";
      
      setStreamingResponse('');
      
      // Simulate streaming word by word
      const words = responseText.split(' ');
      for (let i = 0; i < words.length; i++) {
        await new Promise(resolve => setTimeout(resolve, 100)); // 100ms delay
        setStreamingResponse(prev => prev + (i > 0 ? ' ' : '') + words[i]);
      }
      
      // Add to messages when complete
      setTimeout(() => {
        addBotMessage(responseText);
        setStreamingResponse('');
        setIsLoading(false);
      }, 500);
    } catch (error) {
      addErrorMessage("Error streaming response: " + error.message);
      setIsLoading(false);
    }
  };

  const handleSend = async () => {
    if (!inputValue.trim()) return;
    
    addUserMessage(inputValue);
    const userMessage = inputValue;
    setInputValue('');
    setIsLoading(true);
    
    try {
      // Simple response for demo
      const responses = [
        "I'm processing your query with my super intelligent capabilities!",
        "Thanks for your question. I'm leveraging multiple AI models to give you the best answer.",
        "Interesting point! Let me analyze this with my advanced reasoning capabilities.",
        "I understand what you're asking. Let me provide a comprehensive response."
      ];
      
      const randomResponse = responses[Math.floor(Math.random() * responses.length)];
      setTimeout(() => {
        addBotMessage(randomResponse);
        setIsLoading(false);
      }, 1000);
    } catch (error) {
      addErrorMessage("Error: " + error.message);
      setIsLoading(false);
    }
  };

  const handleKeyPress = (e) => {
    if (e.key === 'Enter' && !e.shiftKey) {
      e.preventDefault();
      handleSend();
    }
  };

  return (
    <div className="min-h-screen bg-gradient-to-br from-purple-50 to-cyan-50 py-12 px-4 sm:px-6 lg:px-8">
      <div className="max-w-4xl mx-auto">
        <div className="text-center mb-12">
          <h1 className="text-4xl font-bold text-gray-900 mb-4">Super Intelligent Trendy Assistant</h1>
          <p className="text-xl text-gray-600">
            Powered by Multiple AI Models for Ultimate Intelligence
          </p>
        </div>

        <div className="grid grid-cols-1 lg:grid-cols-3 gap-8">
          {/* Main Chat Interface */}
          <div className="lg:col-span-2 bg-white rounded-2xl shadow-xl p-6">
            <div className="flex justify-between items-center mb-6">
              <h2 className="text-2xl font-bold text-gray-900">AI Conversation</h2>
              <div className="flex items-center space-x-2">
                <span className="text-sm text-gray-500">Model:</span>
                <select 
                  value={activeModel}
                  onChange={(e) => setActiveModel(e.target.value)}
                  className="border border-gray-300 rounded-lg px-3 py-1 text-sm"
                  disabled={isLoading}
                >
                  <option value="fast">GPT-5 Nano (Fast)</option>
                  <option value="reasoning">DeepSeek Reasoner</option>
                  <option value="creative">Claude Sonnet 4</option>
                  <option value="education">Gemini 2.0 Flash</option>
                </select>
              </div>
            </div>

            {/* Messages Area */}
            <div className="h-96 overflow-y-auto mb-6 p-4 bg-gray-50 rounded-xl">
              {messages.map((message) => (
                <div
                  key={message.id}
                  className={`mb-4 p-4 rounded-lg ${
                    message.sender === 'user'
                      ? 'bg-blue-100 border border-blue-200 ml-8'
                      : message.sender === 'error'
                      ? 'bg-red-100 border border-red-200'
                      : 'bg-gray-100 border border-gray-200 mr-8'
                  }`}
                >
                  <div className="flex justify-between items-start">
                    <div>
                      <span className={`font-medium ${
                        message.sender === 'user' ? 'text-blue-700' : 
                        message.sender === 'error' ? 'text-red-700' : 'text-gray-700'
                      }`}>
                        {message.sender === 'user' ? 'You' : message.sender === 'error' ? 'Error' : 'Trendy AI'}
                      </span>
                      <p className="mt-2 text-gray-800 whitespace-pre-wrap">{message.text}</p>
                    </div>
                    <span className="text-xs text-gray-500 ml-2">
                      {message.timestamp.toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' })}
                    </span>
                  </div>
                </div>
              ))}
              
              {streamingResponse && (
                <div className="mb-4 p-4 rounded-lg bg-gray-100 border border-gray-200 mr-8">
                  <div className="flex justify-between items-start">
                    <div>
                      <span className="font-medium text-gray-700">Trendy AI (Streaming)</span>
                      <p className="mt-2 text-gray-800 whitespace-pre-wrap">{streamingResponse}<span className="inline-block w-2 h-4 bg-gray-800 ml-1 animate-pulse"></span></p>
                    </div>
                  </div>
                </div>
              )}
              
              {isLoading && !streamingResponse && (
                <div className="mb-4 p-4 rounded-lg bg-gray-100 border border-gray-200">
                  <div className="flex space-x-2">
                    <div className="w-3 h-3 bg-gray-400 rounded-full animate-bounce"></div>
                    <div className="w-3 h-3 bg-gray-400 rounded-full animate-bounce delay-75"></div>
                    <div className="w-3 h-3 bg-gray-400 rounded-full animate-bounce delay-150"></div>
                  </div>
                </div>
              )}
            </div>

            {/* Input Area */}
            <div className="flex space-x-2">
              <textarea
                value={inputValue}
                onChange={(e) => setInputValue(e.target.value)}
                onKeyPress={handleKeyPress}
                placeholder="Ask Trendy anything..."
                className="flex-1 border border-gray-300 rounded-lg px-4 py-3 text-sm resize-none focus:outline-none focus:ring-2 focus:ring-brand-cyan focus:border-transparent"
                rows="2"
                disabled={isLoading}
              />
              <button
                onClick={handleSend}
                disabled={isLoading || !inputValue.trim()}
                className="bg-brand-cyan text-white rounded-lg px-6 py-3 hover:bg-brand-navy transition-colors disabled:opacity-50 disabled:cursor-not-allowed"
              >
                Send
              </button>
              <button
                onClick={handleStreamResponse}
                disabled={isLoading || !inputValue.trim()}
                className="bg-purple-600 text-white rounded-lg px-6 py-3 hover:bg-purple-700 transition-colors disabled:opacity-50 disabled:cursor-not-allowed"
              >
                Stream
              </button>
            </div>
          </div>

          {/* Specialized Capabilities Panel */}
          <div className="space-y-6">
            {/* Model Capabilities */}
            <div className="bg-white rounded-2xl shadow-xl p-6">
              <h3 className="text-xl font-bold text-gray-900 mb-4">AI Model Capabilities</h3>
              <div className="space-y-4">
                <button
                  onClick={() => handleSpecializedQuery('creative')}
                  disabled={isLoading}
                  className="w-full text-left p-4 bg-gradient-to-r from-purple-100 to-pink-100 rounded-lg border border-purple-200 hover:from-purple-200 hover:to-pink-200 transition-colors"
                >
                  <div className="font-semibold text-purple-800">🎨 Creative Insights</div>
                  <div className="text-sm text-purple-600 mt-1">Claude Sonnet 4</div>
                </button>
                
                <button
                  onClick={() => handleSpecializedQuery('reasoning')}
                  disabled={isLoading}
                  className="w-full text-left p-4 bg-gradient-to-r from-blue-100 to-cyan-100 rounded-lg border border-blue-200 hover:from-blue-200 hover:to-cyan-200 transition-colors"
                >
                  <div className="font-semibold text-blue-800">🧠 Logical Reasoning</div>
                  <div className="text-sm text-blue-600 mt-1">DeepSeek Reasoner</div>
                </button>
                
                <button
                  onClick={() => handleSpecializedQuery('education')}
                  disabled={isLoading}
                  className="w-full text-left p-4 bg-gradient-to-r from-green-100 to-teal-100 rounded-lg border border-green-200 hover:from-green-200 hover:to-teal-200 transition-colors"
                >
                  <div className="font-semibold text-green-800">📚 Education Expertise</div>
                  <div className="text-sm text-green-600 mt-1">Gemini 2.0 Flash</div>
                </button>
              </div>
            </div>

            {/* Function Calling Demo */}
            <div className="bg-white rounded-2xl shadow-xl p-6">
              <h3 className="text-xl font-bold text-gray-900 mb-4">System Integration</h3>
              <div className="space-y-3">
                <div className="p-3 bg-yellow-50 rounded-lg border border-yellow-200">
                  <div className="font-medium text-yellow-800">📊 Course Database</div>
                  <div className="text-sm text-yellow-600">Access real course information</div>
                </div>
                
                <div className="p-3 bg-indigo-50 rounded-lg border border-indigo-200">
                  <div className="font-medium text-indigo-800">👤 User Profiles</div>
                  <div className="text-sm text-indigo-600">Personalized recommendations</div>
                </div>
                
                <div className="p-3 bg-red-50 rounded-lg border border-red-200">
                  <div className="font-medium text-red-800">📈 Learning Analytics</div>
                  <div className="text-sm text-red-600">Progress tracking & insights</div>
                </div>
              </div>
            </div>

            {/* Super Intelligence Benefits */}
            <div className="bg-gradient-to-br from-purple-600 to-indigo-700 rounded-2xl shadow-xl p-6 text-white">
              <h3 className="text-xl font-bold mb-4">Super Intelligence Benefits</h3>
              <ul className="space-y-2 text-purple-100">
                <li className="flex items-start">
                  <span className="text-green-300 mr-2">✓</span>
                  <span>Context-aware conversations</span>
                </li>
                <li className="flex items-start">
                  <span className="text-green-300 mr-2">✓</span>
                  <span>Multi-model specialization</span>
                </li>
                <li className="flex items-start">
                  <span className="text-green-300 mr-2">✓</span>
                  <span>Real-time streaming responses</span>
                </li>
                <li className="flex items-start">
                  <span className="text-green-300 mr-2">✓</span>
                  <span>System integration capabilities</span>
                </li>
                <li className="flex items-start">
                  <span className="text-green-300 mr-2">✓</span>
                  <span>Continuous learning & adaptation</span>
                </li>
              </ul>
            </div>
          </div>
        </div>

        {/* Implementation Guide */}
        <div className="mt-12 bg-white rounded-2xl shadow-xl p-8">
          <h2 className="text-2xl font-bold text-gray-900 mb-6">How to Make Trendy Super Intelligent</h2>
          
          <div className="grid grid-cols-1 md:grid-cols-2 gap-8">
            <div>
              <h3 className="text-xl font-semibold text-gray-900 mb-4">1. Multi-Model Architecture</h3>
              <ul className="space-y-2 text-gray-600">
                <li>• GPT-5 Nano for fast responses</li>
                <li>• DeepSeek Reasoner for complex analysis</li>
                <li>• Claude Sonnet 4 for creative content</li>
                <li>• Gemini 2.0 Flash for education expertise</li>
              </ul>
            </div>
            
            <div>
              <h3 className="text-xl font-semibold text-gray-900 mb-4">2. Function Calling Integration</h3>
              <ul className="space-y-2 text-gray-600">
                <li>• Connect to course database</li>
                <li>• Access user profiles</li>
                <li>• Retrieve learning analytics</li>
                <li>• Execute system actions</li>
              </ul>
            </div>
            
            <div>
              <h3 className="text-xl font-semibold text-gray-900 mb-4">3. Advanced Features</h3>
              <ul className="space-y-2 text-gray-600">
                <li>• Real-time response streaming</li>
                <li>• Conversation context memory</li>
                <li>• Personalized learning paths</li>
                <li>• Adaptive difficulty adjustment</li>
              </ul>
            </div>
            
            <div>
              <h3 className="text-xl font-semibold text-gray-900 mb-4">4. Continuous Improvement</h3>
              <ul className="space-y-2 text-gray-600">
                <li>• User feedback integration</li>
                <li>• Performance analytics</li>
                <li>• Model fine-tuning</li>
                <li>• Knowledge base expansion</li>
              </ul>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
};

export default SuperIntelligentTrendyDemo;