import React, { useState } from 'react';
import './CourseCreator.css';

const CourseCreator = () => {
  const [course, setCourse] = useState({
    title: '',
    description: '',
    category: '',
    level: 'beginner',
    price: 0,
    thumbnail: '',
    modules: [
      {
        id: Date.now(),
        title: 'Module 1',
        description: '',
        lessons: [
          {
            id: Date.now() + 1,
            title: 'Lesson 1',
            content: '',
            duration: 10,
            order: 1
          }
        ]
      }
    ]
  });

  const [aiTopic, setAiTopic] = useState('');
  const [isGenerating, setIsGenerating] = useState(false);

  // Handle course field changes
  const handleCourseChange = (field, value) => {
    setCourse(prev => ({
      ...prev,
      [field]: value
    }));
  };

  // Handle module field changes
  const handleModuleChange = (moduleId, field, value) => {
    setCourse(prev => ({
      ...prev,
      modules: prev.modules.map(module => 
        module.id === moduleId 
          ? { ...module, [field]: value } 
          : module
      )
    }));
  };

  // Handle lesson field changes
  const handleLessonChange = (moduleId, lessonId, field, value) => {
    setCourse(prev => ({
      ...prev,
      modules: prev.modules.map(module => 
        module.id === moduleId 
          ? {
              ...module,
              lessons: module.lessons.map(lesson => 
                lesson.id === lessonId 
                  ? { ...lesson, [field]: value } 
                  : lesson
              )
            }
          : module
      )
    }));
  };

  // Add a new module
  const addModule = () => {
    const newModule = {
      id: Date.now(),
      title: `Module ${course.modules.length + 1}`,
      description: '',
      lessons: [
        {
          id: Date.now() + Math.floor(Math.random() * 1000),
          title: 'New Lesson',
          content: '',
          duration: 10,
          order: 1
        }
      ]
    };
    
    setCourse(prev => ({
      ...prev,
      modules: [...prev.modules, newModule]
    }));
  };

  // Add a new lesson to a module
  const addLesson = (moduleId) => {
    const newLesson = {
      id: Date.now() + Math.floor(Math.random() * 1000),
      title: 'New Lesson',
      content: '',
      duration: 10,
      order: course.modules.find(m => m.id === moduleId).lessons.length + 1
    };
    
    setCourse(prev => ({
      ...prev,
      modules: prev.modules.map(module => 
        module.id === moduleId 
          ? { ...module, lessons: [...module.lessons, newLesson] } 
          : module
      )
    }));
  };

  // Remove a module
  const removeModule = (moduleId) => {
    if (course.modules.length <= 1) return;
    
    setCourse(prev => ({
      ...prev,
      modules: prev.modules.filter(module => module.id !== moduleId)
    }));
  };

  // Remove a lesson
  const removeLesson = (moduleId, lessonId) => {
    setCourse(prev => ({
      ...prev,
      modules: prev.modules.map(module => 
        module.id === moduleId 
          ? { 
              ...module, 
              lessons: module.lessons.filter(lesson => lesson.id !== lessonId) 
            }
          : module
      )
    }));
  };

  // Generate AI content for a lesson
  const generateAiContent = async (moduleId, lessonId) => {
    if (!aiTopic.trim()) return;
    
    setIsGenerating(true);
    
    try {
      // Simulate AI content generation
      // In a real implementation, this would call an AI service
      const generatedContent = `<h2>${aiTopic}</h2>
<p>This is AI-generated content about ${aiTopic}. In a real implementation, this would be generated by calling an AI service like OpenAI or Anthropic.</p>

<h3>Key Points</h3>
<ul>
  <li>Point 1 about ${aiTopic}</li>
  <li>Point 2 about ${aiTopic}</li>
  <li>Point 3 about ${aiTopic}</li>
</ul>

<h3>Practical Example</h3>
<pre><code>// Sample code related to ${aiTopic}
console.log("This is a sample code block for ${aiTopic}");
</code></pre>

<p>Try experimenting with ${aiTopic} in the playground to reinforce your learning.</p>`;
      
      handleLessonChange(moduleId, lessonId, 'content', generatedContent);
    } catch (error) {
      console.error('Error generating AI content:', error);
    } finally {
      setIsGenerating(false);
    }
  };

  // Save the course
  const saveCourse = () => {
    // In a real implementation, this would send the course data to the backend
    console.log('Saving course:', course);
    alert('Course saved successfully! In a real implementation, this would be sent to the backend.');
  };

  return (
    <div className="course-creator">
      <div className="creator-header">
        <h1>Course Creator</h1>
        <div className="header-actions">
          <button className="btn btn-outline" onClick={addModule}>
            Add Module
          </button>
          <button className="btn btn-primary" onClick={saveCourse}>
            Save Course
          </button>
        </div>
      </div>

      <div className="creator-content">
        {/* Course Metadata */}
        <div className="course-metadata">
          <h2>Course Information</h2>
          <div className="form-group">
            <label htmlFor="course-title">Course Title</label>
            <input
              type="text"
              id="course-title"
              value={course.title}
              onChange={(e) => handleCourseChange('title', e.target.value)}
              placeholder="Enter course title"
            />
          </div>
          
          <div className="form-group">
            <label htmlFor="course-description">Description</label>
            <textarea
              id="course-description"
              value={course.description}
              onChange={(e) => handleCourseChange('description', e.target.value)}
              placeholder="Enter course description"
              rows="3"
            />
          </div>
          
          <div className="form-row">
            <div className="form-group">
              <label htmlFor="course-category">Category</label>
              <select
                id="course-category"
                value={course.category}
                onChange={(e) => handleCourseChange('category', e.target.value)}
              >
                <option value="">Select a category</option>
                <option value="web-development">Web Development</option>
                <option value="ai-ml">AI & Machine Learning</option>
                <option value="digital-marketing">Digital Marketing</option>
                <option value="data-science">Data Science</option>
                <option value="cybersecurity">Cybersecurity</option>
              </select>
            </div>
            
            <div className="form-group">
              <label htmlFor="course-level">Level</label>
              <select
                id="course-level"
                value={course.level}
                onChange={(e) => handleCourseChange('level', e.target.value)}
              >
                <option value="beginner">Beginner</option>
                <option value="intermediate">Intermediate</option>
                <option value="advanced">Advanced</option>
              </select>
            </div>
            
            <div className="form-group">
              <label htmlFor="course-price">Price ($)</label>
              <input
                type="number"
                id="course-price"
                value={course.price}
                onChange={(e) => handleCourseChange('price', parseFloat(e.target.value) || 0)}
                min="0"
                step="10"
              />
            </div>
          </div>
        </div>

        {/* Modules and Lessons */}
        <div className="course-modules">
          {course.modules.map((module, moduleIndex) => (
            <div key={module.id} className="module-section">
              <div className="module-header">
                <h3>Module {moduleIndex + 1}: {module.title}</h3>
                <div className="module-actions">
                  <button 
                    className="btn btn-small btn-outline"
                    onClick={() => addLesson(module.id)}
                  >
                    Add Lesson
                  </button>
                  {course.modules.length > 1 && (
                    <button 
                      className="btn btn-small btn-danger"
                      onClick={() => removeModule(module.id)}
                    >
                      Remove Module
                    </button>
                  )}
                </div>
              </div>
              
              <div className="module-form">
                <div className="form-group">
                  <label htmlFor={`module-title-${module.id}`}>Module Title</label>
                  <input
                    type="text"
                    id={`module-title-${module.id}`}
                    value={module.title}
                    onChange={(e) => handleModuleChange(module.id, 'title', e.target.value)}
                    placeholder="Enter module title"
                  />
                </div>
                
                <div className="form-group">
                  <label htmlFor={`module-description-${module.id}`}>Description</label>
                  <textarea
                    id={`module-description-${module.id}`}
                    value={module.description}
                    onChange={(e) => handleModuleChange(module.id, 'description', e.target.value)}
                    placeholder="Enter module description"
                    rows="2"
                  />
                </div>
              </div>
              
              <div className="module-lessons">
                <h4>Lessons</h4>
                {module.lessons.map((lesson, lessonIndex) => (
                  <div key={lesson.id} className="lesson-card">
                    <div className="lesson-header">
                      <h5>Lesson {lessonIndex + 1}: {lesson.title}</h5>
                      <button 
                        className="btn btn-small btn-danger"
                        onClick={() => removeLesson(module.id, lesson.id)}
                      >
                        Remove
                      </button>
                    </div>
                    
                    <div className="lesson-form">
                      <div className="form-group">
                        <label htmlFor={`lesson-title-${lesson.id}`}>Lesson Title</label>
                        <input
                          type="text"
                          id={`lesson-title-${lesson.id}`}
                          value={lesson.title}
                          onChange={(e) => handleLessonChange(module.id, lesson.id, 'title', e.target.value)}
                          placeholder="Enter lesson title"
                        />
                      </div>
                      
                      <div className="form-row">
                        <div className="form-group">
                          <label htmlFor={`lesson-duration-${lesson.id}`}>Duration (minutes)</label>
                          <input
                            type="number"
                            id={`lesson-duration-${lesson.id}`}
                            value={lesson.duration}
                            onChange={(e) => handleLessonChange(module.id, lesson.id, 'duration', parseInt(e.target.value) || 0)}
                            min="1"
                          />
                        </div>
                        
                        <div className="form-group">
                          <label htmlFor={`lesson-order-${lesson.id}`}>Order</label>
                          <input
                            type="number"
                            id={`lesson-order-${lesson.id}`}
                            value={lesson.order}
                            onChange={(e) => handleLessonChange(module.id, lesson.id, 'order', parseInt(e.target.value) || 1)}
                            min="1"
                          />
                        </div>
                      </div>
                      
                      <div className="form-group">
                        <label htmlFor={`lesson-content-${lesson.id}`}>Content</label>
                        <textarea
                          id={`lesson-content-${lesson.id}`}
                          value={lesson.content}
                          onChange={(e) => handleLessonChange(module.id, lesson.id, 'content', e.target.value)}
                          placeholder="Enter lesson content (supports HTML)"
                          rows="6"
                        />
                      </div>
                      
                      <div className="ai-generation">
                        <div className="form-group">
                          <label htmlFor={`ai-topic-${lesson.id}`}>Generate AI Content</label>
                          <div className="ai-input-group">
                            <input
                              type="text"
                              id={`ai-topic-${lesson.id}`}
                              value={aiTopic}
                              onChange={(e) => setAiTopic(e.target.value)}
                              placeholder="Enter topic for AI content generation"
                            />
                            <button 
                              className="btn btn-secondary"
                              onClick={() => generateAiContent(module.id, lesson.id)}
                              disabled={isGenerating || !aiTopic.trim()}
                            >
                              {isGenerating ? 'Generating...' : 'Generate'}
                            </button>
                          </div>
                          <p className="help-text">
                            Enter a topic and click "Generate" to create AI-powered lesson content.
                          </p>
                        </div>
                      </div>
                    </div>
                  </div>
                ))}
              </div>
            </div>
          ))}
        </div>
      </div>
    </div>
  );
};

export default CourseCreator;