import React, { useState, useEffect } from "react";
import { courseService } from "../services";

const FindValidCourses = () => {
    const [courses, setCourses] = useState([]);
    const [loading, setLoading] = useState(true);
    const [error, setError] = useState(null);

    useEffect(() => {
        const fetchCourses = async () => {
            try {
                setLoading(true);
                setError(null);
                
                // Fetch all courses to see what's available
                const courseData = await courseService.getAllCourses();
                console.log('All courses:', courseData);
                setCourses(courseData);
            } catch (err) {
                console.error('Error fetching courses:', err);
                setError(err.message || 'Failed to load courses');
            } finally {
                setLoading(false);
            }
        };
        
        fetchCourses();
    }, []);

    if (loading) {
        return (
            <div className="container mx-auto px-4 py-16 text-center">
                <div className="animate-spin rounded-full h-12 w-12 border-t-2 border-b-2 border-brand-cyan mx-auto mb-4"></div>
                <p>Loading courses...</p>
            </div>
        );
    }

    if (error) {
        return (
            <div className="container mx-auto px-4 py-16">
                <div className="bg-red-50 border border-red-200 rounded-lg p-6 max-w-2xl mx-auto">
                    <h2 className="text-xl font-semibold text-red-800 mb-2">Error Loading Courses</h2>
                    <p className="text-red-600 mb-4">{error}</p>
                    <button 
                        onClick={() => window.location.reload()}
                        className="px-4 py-2 bg-red-600 text-white rounded hover:bg-red-700"
                    >
                        Try Again
                    </button>
                </div>
            </div>
        );
    }

    return (
        <div className="container mx-auto px-4 py-8">
            <h1 className="text-2xl font-bold mb-6">Valid Course IDs</h1>
            
            {courses.length === 0 ? (
                <div className="bg-yellow-50 border border-yellow-200 rounded-lg p-6 text-center">
                    <h2 className="text-xl font-semibold text-yellow-800 mb-2">No Courses Found</h2>
                    <p className="text-yellow-600 mb-4">
                        There are currently no courses in the database. This is normal if courses are being generated by AI.
                    </p>
                    <p className="text-yellow-600">
                        You can generate courses using the AI Course Generator or have an admin upload courses manually.
                    </p>
                </div>
            ) : (
                <div className="bg-white rounded-lg shadow overflow-hidden">
                    <table className="min-w-full divide-y divide-gray-200">
                        <thead className="bg-gray-50">
                            <tr>
                                <th className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                                    Course Title
                                </th>
                                <th className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                                    Valid ID (Use this in URLs)
                                </th>
                                <th className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                                    Modules
                                </th>
                                <th className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                                    Lessons
                                </th>
                            </tr>
                        </thead>
                        <tbody className="bg-white divide-y divide-gray-200">
                            {courses.map((course) => (
                                <tr key={course.id}>
                                    <td className="px-6 py-4 whitespace-nowrap">
                                        <div className="text-sm font-medium text-gray-900">{course.title}</div>
                                    </td>
                                    <td className="px-6 py-4 whitespace-nowrap">
                                        <div className="text-sm text-gray-900 font-mono bg-gray-100 px-2 py-1 rounded">
                                            {course.id}
                                        </div>
                                        <div className="text-xs text-gray-500 mt-1">
                                            <a 
                                                href={`/course/${course.id}`} 
                                                className="text-brand-cyan hover:underline"
                                            >
                                                Test Link
                                            </a>
                                        </div>
                                    </td>
                                    <td className="px-6 py-4 whitespace-nowrap text-sm text-gray-500">
                                        {course.modules?.length || 0}
                                    </td>
                                    <td className="px-6 py-4 whitespace-nowrap text-sm text-gray-500">
                                        {course.modules?.reduce((total, module) => total + (module.lessons?.length || 0), 0) || 0}
                                    </td>
                                </tr>
                            ))}
                        </tbody>
                    </table>
                </div>
            )}
            
            <div className="mt-8 bg-blue-50 border border-blue-200 rounded-lg p-6">
                <h2 className="text-lg font-semibold text-blue-800 mb-2">How to Use Valid Course IDs</h2>
                <p className="text-blue-600 mb-4">
                    To view a course, use the full UUID in the URL like this:
                </p>
                <code className="block bg-gray-800 text-green-400 p-4 rounded mb-4">
                    https://your-domain.com/course/a0eebc99-9c0b-4ef8-bb6d-6bb9bd380a11
                </code>
                <p className="text-blue-600">
                    <strong>Note:</strong> Simple numbers like "3" are not valid UUIDs. Always use the full UUID shown above.
                </p>
            </div>
        </div>
    );
};

export default FindValidCourses;